### ISSUE TITLE
兼容1.8.9 fabric

### ISSUE THREAD

**Issue by 1a2s3d4f1** [JLChnToZ/MCCustomSkinLoader#105]
[Legacy Fabric](https://github.com/Legacy-Fabric) 这个fabric可以在1.8.9使用，也有optifabric能加载optifine。

请问可以兼容1.8.9fabric吗？

**Comment by ZekerZhayard** [comment]
~~如果现在的用不了，你可以自己修改对应混淆表自己编译：~~
[Fabric/Fabric.tsrg](https://github.com/xfl03/MCCustomSkinLoader/blob/5ebee1f1e099217628a039c0ebbc26a7f4445519/Fabric/Fabric.tsrg)
[Vanilla/1.8.9/1.8.9.tsrg](https://github.com/xfl03/MCCustomSkinLoader/blob/5ebee1f1e099217628a039c0ebbc26a7f4445519/Vanilla/1.8.9/1.8.9.tsrg)

[Fabric/mixin.srg](https://github.com/xfl03/MCCustomSkinLoader/blob/5ebee1f1e099217628a039c0ebbc26a7f4445519/Fabric/mixin.srg)
[Vanilla/1.8.9/mixin.srg](https://github.com/xfl03/MCCustomSkinLoader/blob/5ebee1f1e099217628a039c0ebbc26a7f4445519/Vanilla/1.8.9/mixin.srg)

~~顺便再改一下 Mixin 配置文件：~~
[Fabric/resource/mixins.customskinloader.json](https://github.com/xfl03/MCCustomSkinLoader/blob/5ebee1f1e099217628a039c0ebbc26a7f4445519/Fabric/resource/mixins.customskinloader.json)
[Vanilla/1.8.9/resource/mixins.customskinloader.json](https://github.com/xfl03/MCCustomSkinLoader/blob/5ebee1f1e099217628a039c0ebbc26a7f4445519/Vanilla/1.8.9/resource/mixins.customskinloader.json)

**Comment by HowardZHY** [comment]
已经在做了，已经build了一个了，还没试

**Comment by HowardZHY** [comment]
c,我的refmap哪去了

**Comment by HowardZHY** [comment]
https://gist.githubusercontent.com/YetAnotherMcModder/8fae93025c88ca7e08ee29b69c76aab4/raw/50585f8b63249af0af9a26b3d7a6ab0ecc27e16d/mccrash.txt

**Comment by HowardZHY** [comment]
成功了

**Comment by HowardZHY** [comment]
现在基本可用，除了披风渲染错误

**Comment by HowardZHY** [comment]
https://github.com/HowardZHY/CustomSkinLoader-LegacyFabric/releases/tag/Preview

**Comment by HowardZHY** [comment]
https://github.com/HowardZHY/CustomSkinLoader-LegacyFabric/releases/tag/PreRelease
已修复披风问题，等待33回应

**Comment by xfl03** [comment]
@HowardZHY 感谢制作，建议想办法合并入CustomSkinLoader仓库

**Comment by HowardZHY** [comment]
[https://github.com/HowardZHY/CustomSkinLoader-LegacyFabric](https://github.com/HowardZHY/CustomSkinLoader-LegacyFabric/)实在无法并入,完全拿loom和legacy yarn弄的

**Comment by HowardZHY** [comment]
https://github.com/HowardZHY/CustomSkinLoader-LegacyFabric/releases/tag/14.14-LF
