### ISSUE TITLE
箱子内有皮肤头,打开箱子会造成客户端未响应一段时间

### ISSUE THREAD

**Issue by xyblues** [JLChnToZ/MCCustomSkinLoader#11]
如题....以前的版本是没有的 如果有个箱子 里面放有一个皮肤头 打开的一瞬间会未响应大概30秒到三分钟左右

**Comment by xfl03** [comment]
请使用13.5a版本
这个版本特别修复这一问题
当然，目前只有1.9的版本，低于1.9的版本在13.6发布前不会进行更新，您可以在配置文件中先关闭头颅加载。
