### ISSUE TITLE
【提问】有没有固定的发布地址？

### ISSUE THREAD

**Issue by hcoona** [JLChnToZ/MCCustomSkinLoader#12]
请问有没有固定的 build 发布地址，或者是构建说明文档？

**Comment by xfl03** [comment]
目前全部是依赖于手动构建，成品会直接发布至mcbbs，不知您需要什么文档或许我能提供给你？

**Comment by xfl03** [comment]
以及使用gradle进行构建，
ci  https://ci.infstudio.net/job/CustomSkinLoader/

**Comment by hcoona** [comment]
Good Job! 👍
