### ISSUE TITLE
Custom skin prioritization? 

### ISSUE THREAD

**Issue by TheBrinesour56** [JLChnToZ/MCCustomSkinLoader#120]
MCCustom skins doesn't seem to work without deleting the custom skin on minecraft.net, is there a way to have MCCSL be prioritized for client and other users with the mod and have the minectaft.net skin show to everyone else? I want me and my friends to see each other skins but have everyone else see something else.

**Comment by ZekerZhayard** [comment]
if you want to all your friends see your skin, you should make sure you and your friends have installed this mod. And make sure no one use local skin, otherwise, the one who use local skin will not be displayed for other players.

**Comment by TheBrinesour56** [comment]
Yes but I go on servers where mot many people use MCCSL and instead use the official skin on mincraft.net. I want to show a skin to those who don't have the mod and show a different skin who do. I've figured out how to show the MCCSL skin to my friends but not the minecraft.net skin to everyone else without the mod.

**Comment by ZekerZhayard** [comment]
CSL is a client side mod, you can't control what skin will be displayed for other players.
If you are the admin of the server, you can consider to add some server plugins such as [SkinRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/)
