### ISSUE TITLE
crash with sodium according to to many crashes mod

### ISSUE THREAD

**Issue by TecnaGamer** [JLChnToZ/MCCustomSkinLoader#123]
`---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2020-10-27 16:49:48 EDT
Description: Rendering Block Entity

net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:skins/6IoSDilLtzTJr8zt6skE-g
    at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.19)
    at net.minecraft.util.Identifier.<init>(Identifier:41)
    at net.minecraft.util.Identifier.<init>(Identifier:46)
    at customskinloader.fake.FakeSkinManager.loadSkin(FakeSkinManager.java:52)
    at customskinloader.fake.FakeSkinManager.loadSkin(FakeSkinManager.java:48)
    at net.minecraft.client.texture.PlayerSkinProvider.handler$ccb000$inject_loadSkin(PlayerSkinProvider:537)
    at net.minecraft.client.texture.PlayerSkinProvider.loadSkin(PlayerSkinProvider)
    at net.minecraft.client.texture.PlayerSkinProvider.loadSkin(PlayerSkinProvider:60)
    at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.method_3578(SkullBlockEntityRenderer:103)
    at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.render(SkullBlockEntityRenderer:86)
    at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.render(SkullBlockEntityRenderer:65)
    at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.render(SkullBlockEntityRenderer:29)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:107)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:96)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:128)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:96)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:302)
    at net.minecraft.client.render.WorldRenderer.handler$zzh000$onRenderTileEntities(WorldRenderer:4716)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1265)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1023)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
    at net.minecraft.client.MinecraftClient.handler$blo000$afterCrashHandled(MinecraftClient:15344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.main.Main.main(Main:215)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
  Name: minecraft:skull // net.minecraft.class_2631
  Block: Block{minecraft:player_head}[rotation=0]
  Block location: World: (6965,74,6856), Chunk: (at 5,4,8 in 435,428; contains blocks 6960,0,6848 to 6975,255,6863), Region: (13,13; contains chunks 416,416 to 447,447, blocks 6656,0,6656 to 7167,255,7167)
  Block: Block{minecraft:player_head}[rotation=0]
  Block location: World: (6965,74,6856), Chunk: (at 5,4,8 in 435,428; contains blocks 6960,0,6848 to 6975,255,6863), Region: (13,13; contains chunks 416,416 to 447,447, blocks 6656,0,6656 to 7167,255,7167)
  Block Entity NBT: {SkullOwner:{Id:[I;1538130331,375534500,-1791142050,-849099287],Properties:{textures:[{Value:"e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHBzOi8vZmVlZGJhY2subWluZWNyYWZ0Lm5ldC9oYy91c2VyX2ltYWdlcy82SW9TRGlsTHR6VEpyOHp0NnNrRS1nLnBuZyJ9fX0="}]}},x:6965,y:74,z:6856,id:"minecraft:skull"}

-- Affected level --
  All players: 24 total; [class_746['TecnaGamer'/1000245308, l='ClientLevel', x=6994.69, y=43.00, z=6843.59], class_745['yungbottomtext'/1000242183, l='ClientLevel', x=6974.87, y=43.00, z=6843.39], class_745['Omegagirl7'/1000244181, l='ClientLevel', x=6962.20, y=43.00, z=6841.30], class_745['COMBAT8671'/1000243537, l='ClientLevel', x=6984.85, y=43.00, z=6858.79], class_745['aArtVic'/1000239593, l='ClientLevel', x=6991.04, y=43.50, z=6849.59], class_745['SadCloudy'/1000241464, l='ClientLevel', x=6989.42, y=43.50, z=6834.06], class_745['AngryBread_'/1000214577, l='ClientLevel', x=6989.98, y=43.50, z=6847.70], class_745['Frxnkey'/1000238594, l='ClientLevel', x=6987.51, y=43.00, z=6832.35], class_745['Regasian'/1000236649, l='ClientLevel', x=6979.68, y=43.00, z=6837.49], class_745['CircleStrqfe'/1000229170, l='ClientLevel', x=6981.95, y=43.00, z=6832.82], class_745['ZenithHorizon'/1000214393, l='ClientLevel', x=6986.32, y=43.00, z=6837.83], class_745['AceTheExaltdKing'/1000245016, l='ClientLevel', x=6982.78, y=43.00, z=6833.82], class_745['ImNexty626'/1000242411, l='ClientLevel', x=6981.92, y=43.00, z=6831.03], class_745['Mahi_Mahi_'/1000245160, l='ClientLevel', x=6981.33, y=43.00, z=6830.34], class_745['Venomous_Arrow'/1000239370, l='ClientLevel', x=6981.53, y=44.08, z=6833.84], class_745['Lillia___Fan'/1000225425, l='ClientLevel', x=6997.15, y=43.00, z=6848.00], class_745['8YearOld'/1000231689, l='ClientLevel', x=7001.70, y=63.00, z=6841.30], class_745['Lord_maselko136'/1000239340, l='ClientLevel', x=6995.28, y=43.85, z=6840.21], class_745['kacpitoziomal'/1000239297, l='ClientLevel', x=7010.50, y=43.00, z=6838.33], class_745['LimboMC'/1000238196, l='ClientLevel', x=7021.47, y=43.00, z=6831.44], class_745['YY_DigZz'/1000235830, l='ClientLevel', x=7010.31, y=43.00, z=6836.72], class_745['Rodeus'/1000211371, l='ClientLevel', x=7010.20, y=43.00, z=6830.82], class_745['jetplaying'/1000240879, l='ClientLevel', x=6982.50, y=43.50, z=6837.50], class_745['Strider314'/1000239608, l='ClientLevel', x=6982.50, y=43.42, z=6837.50]]
  Chunk stats: SodiumChunkCache: 529
  Level dimension: minecraft:overworld
  Level spawn location: World: (6997,26,6985), Chunk: (at 5,1,9 in 437,436; contains blocks 6992,0,6976 to 7007,255,6991), Region: (13,13; contains chunks 416,416 to 447,447, blocks 6656,0,6656 to 7167,255,7167)
  Level time: 99749 game time, 4000 day time
  Server brand: Waterfall <- Tuinity
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Linux (amd64) version 5.8.0-7625-generic
  Java Version: 11.0.9, Ubuntu
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
  Memory: 761321192 bytes (726 MB) / 1879048192 bytes (1792 MB) up to 4294967296 bytes (4096 MB)
  CPUs: 4
  JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Sodium (sodium), CustomSkinLoader (customskinloader), Fabric Loader (fabricloader)
  Fabric Mods: afktape: AFKTape 1.1.1
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               antighost: AntiGhost 1.16.2-fabric0.17.2-1.1.3
               artifice: Artifice 0.13.1+1.16.2-rc1
               authme: Auth Me 1.4.0
               autoconfig1u: Auto Config v1 Updated 3.2.2
               bedrockify: BedrockIfy 0.1.8
               bendy-lib: Bendy api 0.2.2
               blue_endless_jankson: jankson 1.2.0
               boringtweaks: Boring Tweaks 1.0.0+1.16.3
               cakechomps: Cake Chomps 1.2.0-1.16.3
               capes: Capes 1.1.1
               carpet: Carpet Mod in Fabric 1.4.12
               carpet-tis-addition: Carpet TIS Addition 1.3.0
               chat_heads: Chat Heads 0.1.2+1.16.2
               cherry: Cherry 1.3.1
               chesttracker: Chest Tracker 0.7.9
               clickthrough: ClickThrough 1.16.2-fabric0.17.2-0.3
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.8
               cloth-config2: Cloth Config v4 4.8.2
               cmdkeybind: Command Macros 1.5.1-1.16
               colormatic: Colormatic 2.2.7+mc.1.16.3
               com_electronwill_night-config_core: core 3.6.0
               com_electronwill_night-config_toml: toml 3.6.0
               com_github_zafarkhaja_java-semver: java-semver 0.9.0
               completeconfig: CompleteConfig 0.5.0
               continuebutton: Continue Button 1.0.1
               cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
               crowdin-translate: CrowdinTranslate 1.1
               customskinloader: CustomSkinLoader 14.13-SNAPSHOT-190
               customstars: Custom Stars 0.4.1
               customvoid: Custom Void 0.2
               ditn: Doot in the Night 1.0.0+1.16.3
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               ears: Ears 1.0.1
               eer: Erroring Entity Remover 1.0.0
               elytra_bounce: Elytra Hopping 0.1.0+1.16.1
               emotecraft: Emotecraft 1.1.0
               enchantedtooltips: Enchanted ToolTips 1.3.4-1.16
               fabric: Fabric API 0.24.2+build.413-1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
               fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c6fa
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5fa
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5ffa
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.1+a4467d2a95
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
               fabricloader: Fabric Loader 0.10.1+build.209
               fabricskyboxes: FabricSkyBoxes 0.3.0
               fiber: fiber 0.23.0-2
               firstperson: FirstpersonModel 1.3.0
               flexfov: Flex FOV 1.1.3
               gbfabrictools: GBfabrictools 1.2.3+1.16.2
               illuminations: Illuminations 1.2.2
               inventorytabs: Inventory Tabs 0.2.3-1.16.3
               itemmodelfix: Item Model Fix 0.2.4
               jankson: Jankson 3.0.1+j1.2.0
               kronhud: KronHUD 1.1.1
               kyrptconfig: Kytpt Config 1.1.4-1.16
               lambdabettergrass: LambdaBetterGrass 1.0.1+1.16.3
               lambdynlights: LambDynamicLights 1.3.1+1.16.3
               libgui: LibGui 3.2.1+1.16.3
               lithium: Lithium 0.5.6
               loadcatcher: Entrypoint Catcher 2.0.0
               logintoast: Login Toast 0.2
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               minecraft: Minecraft 1.16.3
               mm: Manningham Mills 2.1
               modid: Damage Tilt 1.16-fabric-0.1.0
               modmenu: Mod Menu 1.14.6+build.31
               multiconnect: MultiConnect 1.3.30
               multiconnect-api: MultiConnect API 1.3.30
               nostrip: No Strip 1.1.0-1.16.2+
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               numericping: NumericPing 1.0.2-fabric1.16.3
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               oldwalkinganimation: Old Walking Animation 1.0.0
               openj9compat: OpenJ9 compatibility fixes 1.0.0
               org_apache_httpcomponents_httpclient: httpclient 4.5.10
               org_apache_httpcomponents_httpcore: httpcore 4.4.12
               org_apache_httpcomponents_httpmime: httpmime 4.5.10
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_sandboxpowered_simpleeventhandler: SimpleEventHandler 2.0.3
               org_yaml_snakeyaml: snakeyaml 1.26
               perspectivemod: Perspective Mod Redux 0.0.4
               petowner: Pet Owner 1.16.2+-1.6.1
               polish: Polish 1.0.3
               recently_used: Recently Used 0.2.2+1.16.1
               replaymod: Replay Mod 1.16.3-2.4.5
               rocks_rdil_simpleconfig: simpleconfig 2.0.0
               sandbox: Sandbox 0.4.36
               sandbox-base: sandbox-base 0.4.36
               sandbox-rendering: sandbox-rendering 0.4.36
               sandbox-resources: sandbox-resources 0.4.36
               sandbox_bootstrap: Sandbox Bootstrap 0.2.17
               servertick: Server Tick 1.3
               shuffle: Shuffle 1.3.0
               shulkerboxtooltip: Shulker Box Tootip 2.2.1+1.16.3
               skinswapper: Minecraft Skin Change Mod 2.0.1
               slight-gui-modifications: 'Slight' GUI Modifications 1.5.0
               slotlock: SlotLock 1.0-BETA
               slyde: Slyde 1.1
               smoothboot: Smooth Boot 1.0.0
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               soaring-clouds: Soaring Clouds 1.2.0-1.16
               sodium: Sodium 0.1.0
               spruceui: SpruceUI 1.6.4
               taternetworking: Tater Networking 1.0.2
               tooltipfix: ToolTip Fix 1.0.2-1.16
               toomanybinds: Too Many Binds 0.3.0+1.16.3
               uglyscoreboardfix: Ugly Scoreboard Fix 0.2.0
               viabackwards: ViaBackwards 3.1.1
               viafabric: ViaFabric 0.2.15-SNAPSHOT+build-568.1-mc-1.16
               viarewind: ViaRewind 1.5.1
               viaversion: ViaVersion 3.1.1
               visp: Visp 0.0.3
  Launched Version: fabric-loader-0.10.1+build.209-1.16.3
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: Mesa Intel(R) Iris(R) Graphics 6100 (BDW GT3) GL version 4.6 (Compatibility Profile) Mesa 20.2.1, Intel
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'sandbox'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: slightguimodifications:cts_textures, replaymod_lang (incompatible), vanilla, fabric/artifice, fabric/authme, fabric/autoconfig1u, fabric/capes, fabric/carpet, fabric/chat_heads, fabric/cloth-config2, fabric/elytra_bounce, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-language-kotlin, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, fabric/fabricskyboxes, fabric/flexfov, fabric/illuminations (incompatible), fabric/jankson, fabric/kronhud, fabric/lithium, fabric/logintoast, fabric/malilib (incompatible), fabric/mm, fabric/modmenu, fabric/oldwalkinganimation, fabric/openj9compat, fabric/perspectivemod (incompatible), fabric/petowner, fabric/replaymod (incompatible), fabric/sandbox (incompatible), fabric/servertick, fabric/shulkerboxtooltip, fabric/skinswapper, fabric/slight-gui-modifications, fabric/slotlock, fabric/smoothscrollingeverywhere, fabric/sodium, fabric/uglyscoreboardfix, fabric/antighost, fabric/cakechomps, fabric/carpet-tis-addition, fabric/chesttracker, fabric/clickthrough, fabric/colormatic, fabric/firstperson, fabric/gbfabrictools, fabric/lambdabettergrass, fabric/lambdynlights, fabric/libgui, fabric/modid, fabric/nostrip, fabric/okzoomer, fabric/shuffle, fabric/soaring-clouds, fabric/spruceui, fabric/taternetworking, fabric/visp, fabric/notenoughcrashes, fabric/customstars, fabric/ears, fabric/numericping, file/NewDefault+v1.34[MC1.16.2+].zip, fabric/amecsapi, fabric/bedrockify, fabric/continuebutton, fabric/customvoid, fabric/ditn, fabric/toomanybinds, fabric/viafabric, fabric/viaversion, fabric/afktape, fabric/bendy-lib, fabric/boringtweaks, fabric/cherry, fabric/cmdkeybind, fabric/emotecraft, fabric/enchantedtooltips, fabric/inventorytabs, fabric/itemmodelfix, fabric/multiconnect, fabric/multiconnect-api, fabric/recently_used, fabric/viabackwards, fabric/viarewind
  Current Language: English (US)
  CPU: 4x Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0`

**Comment by xfl03** [comment]
`https://feedback.minecraft.net/hc/user_images/6IoSDilLtzTJr8zt6skE-g.png`
It's a strange url, and the result is 404 not found.
Please contact the author of the map to remove the skull in `6965,74,6856` .
