### ISSUE TITLE
Fabric服务端无法配置所选的皮肤站

### ISSUE THREAD

**Issue by 1shin-7** [JLChnToZ/MCCustomSkinLoader#125]
在Fabric 1.15.2服务端中使用最新版csl，但它在加载成功的情况下却不会在根目录创建CustomSkinLoader文件夹，也不会读取CustomSkinLoader内的数据.

**Comment by ZekerZhayard** [comment]
CustomSkinLoader 是纯客户端 mod，无需装进服务端

**Comment by 1shin-7** [comment]
> CustomSkinLoader 是纯客户端 mod，无需装进服务端



> CustomSkinLoader 是纯客户端 mod，无需装进服务端

为了玩家体验，不把csl装进服务器难道让玩家自己装半天，结果还没配置上皮肤站？试问那个管理/腐竹会有这么多时间一个一个教群员？再者介绍页也说了这也是个server-side mod，而实际的测试也显示这在服务端是有效的。

**Comment by ZekerZhayard** [comment]
> 介绍页也说了这也是个server-side mod  

CustomSkinLoader 从未宣称过自己是 server-side mod

> 不把csl装进服务器难道让玩家自己装半天，结果还没配置上皮肤站？  

目前主流的做法是服主配发客户端中带有配置好的 CustomSkinLoader mod

**Comment by Neubulae** [comment]
:concern:
不是你这是要干嘛，如果你想要皮肤那装个FabricTailor或者使用外置登录不行吗

**Comment by xfl03** [comment]
CustomSkinLoader 是 client-side mod，无需装进服务端也不能装进服务端
