### ISSUE TITLE
关于CSL在1.7.10版本的加载

### ISSUE THREAD

**Issue by Kirikure** [JLChnToZ/MCCustomSkinLoader#129]
请问为什么我在使用1.7.10版本的forge1614时，mods文件夹内的CSL没有被加载

**Comment by ZekerZhayard** [comment]
需要提供日志，位于：
- `.minecraft/CustomSkinLoader/CustomSkinLoader.log`
- `.minecraft/logs/fml-client-latest.log`
- `.minecraft/logs/latest.log`

**Comment by xfl03** [comment]
长时间未提供信息，请在提供信息后重新开启issue
