### ISSUE TITLE
默认列表新增皮肤站申请

### ISSUE THREAD

**Issue by DYzjm** [JLChnToZ/MCCustomSkinLoader#13]
我不知道可不可以申请！抱歉！
我想申请加入我的皮肤站！
我在这里看到您的帖子！http://www.mcbbs.net/thread-269807-1-1.html

是否可以添加我的皮肤站为默认皮肤？我的网站永久的！
为了玩家信息安全！我将皮肤站点HTTP升级成为HTTPS加密！配置如下：

参考(注意： 有不少人将HTTPS敲成HTTP    那你就错了！)  
我的网站：  https://www.qy211.com

我给出的配置文件：
{
    "enable": true,
    "loadlist": [
        {
            "name": "SHSZ_PF",
            "type": "CustomSkinAPI",
            "root": "https://www.qy211.com/"
        },
        {
            "name": "Mojang",
            "type": "CustomSkinAPI"
        },
        {
            "name": "SkinMe",
            "type": "CustomSkinAPI",
            "root": "https://www.qy211.com/"
        }
    ]
}

**Comment by xfl03** [comment]
暂时未能通过，因为这是一个基于"Blessing Skin Server"的皮肤站项目，希望可以加入自主开发的内容。如果您还有其他理由，请您继续回复。
