### ISSUE TITLE
Missing License Infomation in file 

### ISSUE THREAD

**Issue by ghost** [JLChnToZ/MCCustomSkinLoader#130]
[crash-2020-12-07_02.06.42-fml.txt](https://github.com/xfl03/MCCustomSkinLoader/files/5650559/crash-2020-12-07_02.06.42-fml.txt)
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/5650560/CustomSkinLoader.log)
[latest.log](https://github.com/xfl03/MCCustomSkinLoader/files/5650561/latest.log)
![Captura](https://user-images.githubusercontent.com/39636228/101312110-b2d83980-3831-11eb-88b4-d55d4d3fc38e.PNG)

**Comment by xfl03** [comment]
Please use 14.13 snapshot.
