### ISSUE TITLE
[Suggestion] Skin work in multiplayer (Only in my perspective)

### ISSUE THREAD

**Issue by barraIhsan** [JLChnToZ/MCCustomSkinLoader#134]
I just download it, and i love it! now I can record a youtube video with it. But the problem is if I join a server, my skin is back to alex / steve. I love to see if were able to change it too. But only in my perspective. In other perspective it still alex. Hope you understand it

**Comment by tnqzh123** [comment]
If you mean you could see your skin in servers but other players can't, that's normal.

Players' skins are delivered by the server you joined, but CSL could only work in your client, cannot effect the server.

If you want other players in the server to see your skin, they should install and configure CSL properly too.
