### ISSUE TITLE
Disable the logs for customskinloader for latest.log?

### ISSUE THREAD

**Issue by Kichura** [JLChnToZ/MCCustomSkinLoader#135]
This isn't really a bug report but rather a question about this mod, Is it possible to disable the logs for this mod so that the logs don't end up becoming flooded with random player skin names and non-understandable contexts?

**Comment by ZekerZhayard** [comment]
Maybe duplicate with https://github.com/xfl03/MCCustomSkinLoader/issues/121
See https://github.com/xfl03/MCCustomSkinLoader/issues/121#issuecomment-702150280

**Comment by Kichura** [comment]
This does not represent itself as a bug but rather a suggestion on making it possible to disable those logs at all when skins/capes are being rendered in.

**Comment by xfl03** [comment]
https://github.com/xfl03/MCCustomSkinLoader/commit/63251c9f5e3d1742e55f0e7e95c64a5d2399d063
