### ISSUE TITLE
Alex Model Skin Appears as Steve Model Skin Upon 2nd (or more) Load on World/Server with Auto Setting

### ISSUE THREAD

**Issue by DB20-official** [JLChnToZ/MCCustomSkinLoader#136]
Local skin was used to load the skin on the server/world. It loads properly on first join but upon joining the 2nd or more times, it always will use Steve skin model instead of Alex one. This can cause the game to crash with other player model-altering mods such as McHorse's Emoticons and MorePlayerModels. Not sure if this behavior is intentional, which is why this issue is being filed to see what can be done.

Minecraft Version: 1.12.2
Forge: 14.23.5.2838
Other Mods: FoamFix, LabyMod3, MoBends, OptiFine, ShoulderSurfing, SmoothFont, and VanillaFix
Shader Active: KUDA Shaders All Versions Lite
Name: LocalSkin
API Type: Legacy
Model: Auto
Skin Resolution: 2048x2048
Actual Skin Model: Alex
CustomSkinLoader Version: 14.11 (forgot to look at Releases page before posting this!!)

**Comment by ZekerZhayard** [comment]
This bug has been fixed in later version, try to use the latest version: https://csl.littleservice.cn/mods/CustomSkinLoader_Forge-14.13-SNAPSHOT-203.jar

**Comment by DB20-official** [comment]
Got the new version, no longer crashes game after switching servers/worlds with other player model-altering mods. Thanks for letting me know!
