### ISSUE TITLE
Transparent cape is not transparent anymore.

### ISSUE THREAD

**Issue by slainless** [JLChnToZ/MCCustomSkinLoader#139]
Hello, i have been using this since 1.12.2, thank you for your amazing mod!

Recently, i tried to migrate to 1.16.4. But, my cape is not transparent anymore (while it is in 1.12.2):

---
Here is the screenshot
![2021-01-12_11 16 30](https://user-images.githubusercontent.com/13495566/104265064-be212380-54c7-11eb-92a5-5203bc3a18ea.png)

Here is how it's supposed to show (taken in 1.12.2):
![2021-01-12_11 24 57](https://user-images.githubusercontent.com/13495566/104265658-0a209800-54c9-11eb-9c35-c62a762ec886.png)

These two version are using the same assets/skin and loaded via local skin:
```json
{
  "name": "LocalSkin",
  "type": "Legacy",
  "checkPNG": false,
  "skin": "LocalSkin/skins/{USERNAME}.png",
  "model": "auto",
  "cape": "LocalSkin/capes/{USERNAME}.png",
  "elytra": "LocalSkin/elytras/{USERNAME}.png"
}
```

**Comment by ZekerZhayard** [comment]
What mod version did you use? This issue has been fixed in https://github.com/xfl03/MCCustomSkinLoader/commit/12441cc37984274260fa49f3226e10d1f7e5e194

**Comment by slainless** [comment]
Forge 14.13 s199
![image](https://user-images.githubusercontent.com/13495566/104268683-743c3b80-54cf-11eb-9d98-c96cb36888ce.png)

Here is the cape:
![Stardusk](https://user-images.githubusercontent.com/13495566/104268864-e57bee80-54cf-11eb-85a0-ec76f0482ec7.png)

**Comment by ZekerZhayard** [comment]
OK, i know what happened.

**Comment by ZekerZhayard** [comment]
Fixed in https://csl.littleservice.cn/mods/CustomSkinLoader_Forge-14.13-SNAPSHOT-212.jar
