### ISSUE TITLE
MCCustomSkinLoader with skinrestorer

### ISSUE THREAD

**Issue by Link0Darck** [JLChnToZ/MCCustomSkinLoader#145]
Hello,
I have a question there is a possibility to retrieve the skins on a database because I use skinrestorer which send the skins on a database view I have created a launcher I would like your mods if it can do this retrieve the skin in the database so my players who play solo have their skin uploaded in the database
thank you in advance for your help
Yours sincerely

**Comment by xfl03** [comment]
I think you can make a backend to read from database and output json in HTTP.
