### ISSUE TITLE
SkinsRestorer 插件问题

### ISSUE THREAD

**Issue by xyblues** [JLChnToZ/MCCustomSkinLoader#15]
SkinsRestorer 插件 是一个让盗版玩家使用正版皮肤的插件
使用指令/skin set 正版玩家昵称 即可更换为正版皮肤
但是和你的皮肤插件联动会有点问题
如果你是正版账号 则无法更换皮肤
如果你不是正版账号 则只能更换一次皮肤
大概是加载优先级的问题?
Minecraft版本1.8
服务端版本1.8.8
插件网址
https://www.spigotmc.org/resources/skinsrestorer.2124/
插件配置 不知道有没有关系
`#Mojang has a limit for getting skins.
#This website uses proxies to get the skin data
#From mojang, so you will not be limited.
#However. If you do not trust mcapi.ca, you can disable that option.
MCAPI:
  Enabled: true
  Get Profile URL: https://mcapi.ca/SR/?player\u003d{username}
  Get SkinProfile URL: https://mcapi.ca/name/uuid/{uuid}`

**Comment by xfl03** [comment]
这是您的第三个issue，下一个issue我不会受理。
不给日志文件，没必要发issue。

**Comment by xyblues** [comment]
非常抱歉 我也没用过github 我也不知道要发什么 
我只是尽力的把我知道的发出来
这个是我使用的测试用户名 dashkjfgh
正因为我喜欢你的MOD 才会提交问题啊.....
[CustomSkinLoader.txt](https://github.com/JLChnToZ/MCCustomSkinLoader/files/264837/CustomSkinLoader.txt)

**Comment by xfl03** [comment]
补充：我自己用 SkinsRestorer 以及 SkinsChanger 在 1.9 工作的非常正常，无论正版还是盗版都没问题

**Comment by xfl03** [comment]
哪个是正版账号？

**Comment by xyblues** [comment]
非常抱歉 
如图 我尝试换了很多次并且关掉游戏重开 依然无法换皮肤
除了 dashkjfgh 是盗版 其余的都是正版的NPC
我本人用自己的XYBlue 的账号 也无法更换 永远是正版皮肤
插件版本与你的MOD版本是最新版 今天下的
![image](https://cloud.githubusercontent.com/assets/15712089/15272019/5333e706-1a98-11e6-8ee8-5b5274971beb.png)

**Comment by xfl03** [comment]
换皮肤的话，要么重启游戏，要么关掉缓存功能，这个不是bug

**Comment by xyblues** [comment]
好的 我试试
