### ISSUE TITLE
How to use for online

### ISSUE THREAD

**Issue by Fern-Evergreen** [JLChnToZ/MCCustomSkinLoader#150]
There are no tutorials of how to use this in an online server, nor how to use hd skins with this, can someone explain it for me

**Comment by barraIhsan** [comment]
Its completely client side, but other people use this mod, can add your username to local, and set the skin. I think the HD Skin its just like optifine, you just put the HD Skin in `.minecraft/CustomSkinLoader/LocalSkin/skins/<your username>`

**Comment by ZekerZhayard** [comment]
@barraIhsan There is lack of tutorials about how to load skins online in English.

There are some skin websites in default CustomSkinLoader load list:
- [Little Skin](https://littlesk.in/)
- [Blessing Skin](https://skin.prinzeugen.net/)
- [ElyBy](https://ely.by)
- [SkinMe](https://www.skinme.cc)
- [GlichlessGames](https://games.glitchless.ru/)

you can sign in one of them and select or upload your skin.
