### ISSUE TITLE
Crash with TRansliterationLib

### ISSUE THREAD

**Issue by ghost** [JLChnToZ/MCCustomSkinLoader#152]
issue:
https://github.com/tr7zw/TRansliterationLib/issues/15
log:
[console log (OptiFine Installed).log](https://github.com/xfl03/MCCustomSkinLoader/files/6253002/console.log.OptiFine.Installed.log)
[crash report (OptiFine not installed).txt](https://github.com/xfl03/MCCustomSkinLoader/files/6253006/crash.report.OptiFine.not.installed.txt)

**Comment by ZekerZhayard** [comment]
Use the latest CustomSkinLoader: https://csl.littleservice.cn/mods/CustomSkinLoader_Forge-14.13-SNAPSHOT-225.jar
