### ISSUE TITLE
Skin is load from Mojang services although i dont have premium acc

### ISSUE THREAD

**Issue by barraIhsan** [JLChnToZ/MCCustomSkinLoader#153]
So i look at the log and suddenly this appear
```
[BarraIhsan INFO] Loading BarraIhsan's profile.
[BarraIhsan INFO] 1/2 Try to load profile from 'Mojang'.
[BarraIhsan INFO] Default profile will be used.
[BarraIhsan INFO] BarraIhsan's profile loaded.
[BarraIhsan INFO] (SkinUrl: http://textures.minecraft.net/texture/d6bfe7add075a982ba4e7277de9ac83ec8a5e2d31990f688948a896f74cbb2b1 , Model: default , CapeUrl: null  , Expiry: 1617519258)
```
I try to look at the [API](https://api.mojang.com/users/profiles/minecraft/BarraIhsan) But it doesn't load, I also search for [NameMC]{https://namemc.com/search?q=BarraIhsan}, its also says available. But strangely enough, the `textures.minecraft.net` is working? Is CustomSkinLoader just upload my skin to the mojang API?

**Comment by ZekerZhayard** [comment]
CustomSkinLoader is not a mod for uploading skin. It just a mod that can load skins and capes from 3rd-party skin websites and supports loading HD skins.

**Comment by barraIhsan** [comment]
So, why thats happened?

**Comment by ZekerZhayard** [comment]
> So, why thats happened?

Because that site is required POST method, but accessing it from internet browser is equivalent to GET method

**Comment by barraIhsan** [comment]
Oh, because of that, CustomSkinLoader think that my skin from MOJANG?

**Comment by ZekerZhayard** [comment]
> Oh, because of that, CustomSkinLoader think that my skin from MOJANG?

CustomSkinLoader has a default 3rd-party skin websites loading list (https://github.com/xfl03/MCCustomSkinLoader/issues/150#issuecomment-813033680), you can modify the order of them in config file (.minecraftt/CustomSkinLoader/CustomSkinLoader.json) so that the mod can load from other skin website first. There is a [Chinese document](https://csl.littleservice.cn/faq/config-csl.html) that explains the meaning of each option in the config file because most of our users are all Chinese. There is no extra GUI in game to modify the config file. You may need to modify it by code editors.

**Comment by barraIhsan** [comment]
> > Oh, because of that, CustomSkinLoader think that my skin from MOJANG?
> 
> CustomSkinLoader has a default 3rd-party skin websites loading list ([#150 (comment)](https://github.com/xfl03/MCCustomSkinLoader/issues/150#issuecomment-813033680)), you can modify the order of them in config file (.minecraftt/CustomSkinLoader/CustomSkinLoader.json) so that the mod can load from other skin website first. There is a [Chinese document](https://csl.littleservice.cn/faq/config-csl.html) that explains the meaning of each option in the config file because most of our users are all Chinese. There is no extra GUI in game to modify the config file. You may need to modify it by code editors.

Yea, I modify it to only Mojang and LocalSkin, but more confusing is why its getting my skin from mojang. Before this, it gonna fail, and customskinloader getting my skin from LocalSkin

**Comment by ZekerZhayard** [comment]
> Yea, I modify it to only Mojang and LocalSkin, but more confusing is why its getting my skin from mojang. Before this, it gonna fail, and customskinloader getting my skin from LocalSkin

- Put your local skin into `${game-folder}/CustomSkinLoader/LocalSkin/skins` and rename your skin file to `${username}.png`
- Modify the order of the loading list (put LocalSkin to the top):
  ```json
  {
    ...
    "loadlist": [
      {
        "name": "LocalSkin",
        "type": "Legacy",
        "checkPNG": true,
        "skin": "LocalSkin/skins/{USERNAME}.png",
        "model": "auto",
        "cape": "LocalSkin/capes/{USERNAME}.png",
        "elytra": "LocalSkin/elytras/{USERNAME}.png"
      },
      {
        "name": "Mojang",
        "type": "MojangAPI",
        "apiRoot": "https://api.mojang.com/",
        "sessionRoot": "https://sessionserver.mojang.com/"
      }
    ],
    ...
  }
  ```

**Comment by barraIhsan** [comment]
Yeah i already do that, and no. I just ask why my skin is getting from mojang, its suppose to NOT get it from mojang, Because I doesn't have Minecraft / Mojang acc

**Comment by ZekerZhayard** [comment]
> Yeah i already do that, and no. I just ask why my skin is getting from mojang, its suppose to NOT get it from mojang, Because I doesn't have Minecraft / Mojang acc

Were you playing an offline server at that time? `Default profile will be used.` means that server sent texture profiles to every players initiative (Yes, the default behavior of online servers is like this, but there are a several server plugin can also do that, one of the popular ones is [SkinRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124), it can be used in offline servers).

**Comment by barraIhsan** [comment]
Oh ok!
