### ISSUE TITLE
No Capes with Littleskin

### ISSUE THREAD

**Issue by ghost** [JLChnToZ/MCCustomSkinLoader#155]
Hey there! I've uploaded my skin and cape on LittleSkin.cn. I can fully see my skin, but my cape isn't visible. How can I fix it?

![no cape](https://i.imgur.com/SKV5dSe.png)

![no cape](https://i.imgur.com/CNfGXOl.png)

**Cape** in **Skin Customizations** is turned ON.

**Comment by ZekerZhayard** [comment]
Can you provide your logs?
`.minecraft/CustomSkinLoader/CustomSkinLoader.log`

**Comment by ghost** [comment]
[Here you go!](https://pastebin.com/raw/sWLSnR5E)

**Comment by ZekerZhayard** [comment]
I checked `https://littlesk.in/csl/lvlythecommander.json` and it reterns 
```json
{"username":"lvlythecommander","skins":{"slim":"b5e8bffb47fdca6178f56140b93e4a1184f68d9b974c65bf465d5cd560634ee4"},"cape":"1e5e86518cfdc53749054f5f66c72fbf8f04a10479975d3e87adbc9572b79ad3"}
```

that's fine. It looks like there is a problem with CDN, please be patient.

**Comment by ghost** [comment]
Of course! Thank you for your time!

**Comment by lovelythecommander** [comment]
I'm not a developer on anything like that, but I looked at `https://littleskin.cn/csl/lvlythecommander.json` too, and there is `"cape":null`, but actually I do have a cape activated. Maybe it is Littleskin's bug?

**Comment by tnqzh123** [comment]
Actually we have a problem with our CDN caches refreshing queue these days. We're still figuring out what caused the problem. Please be patient and we will let you know if we solved it.
