### ISSUE TITLE
Wrong URL requested for littleskin

### ISSUE THREAD

**Issue by PikaGamer** [JLChnToZ/MCCustomSkinLoader#156]
I had issues getting my littleskin skin to show up, even after putting it at the top of the priority list, after some experimentation I found out it was because the config file requests "littlesk.in" instead of Littleskin.cn

**Comment by ZekerZhayard** [comment]
Yes, `https://littlesk.in` is a domain that dedicated to redirects. For users in mainland of China, it will redirect to `https://mcskin.littleservice.cn`, and for other users, it will redirect to `https://littleskin.cn`.
The reason for this design is that users often don’t know the difference between the two URLs and use the wrong URL, which cause some problems when accessing the website.

**Comment by xfl03** [comment]
@tnqzh123
