### ISSUE TITLE
Mojang Api seems to overide the Custom Api's

### ISSUE THREAD

**Issue by Coresixxer** [JLChnToZ/MCCustomSkinLoader#161]
Good day!! I tried to configure this mod for my server yesterday so I decided to test it out with a friend. We tested it out on a cracked server since half of the members were using Cracked MC while me and a few others had Premium accounts. The problem was that the Custom Api's wont load,The mojang one worked since my official skin was restored anyways I knew they wont load since I tried to delete the Mojang Api in the loadlist but once I did that my skin turned to default. What could be causing this problem? Could it be with the server link and What can I do to fix it?

**Comment by ZekerZhayard** [comment]
- CustomSkinLoader is a client side mod, do not install it in server side, and only those who have installed this mod can load the skin 
- Do not download the mod from GitHub Release page, it is an outdated version, check https://littlesk.in/csl-latest to get the latest link
- Can you provide your logs? its in `.miinecraft/CustomSkinLoader/CustomSkinLoader.log`

**Comment by Coresixxer** [comment]
Hi thank you for responding anyways
1.I didn't install it on the server and we both had it installed via Forge 36.1.0 for 1.16.5
2.I believe I downloaded the mod from 9minecraft
3.I will be sending the logs later since I'm on my phone right now. Also should I send it here or should I send you a direct message?

**Comment by ZekerZhayard** [comment]
>I believe I downloaded the mod from 9minecraft  

Do not download mods from 9minecraft, see https://vazkii.net/repost/

**Comment by Coresixxer** [comment]
Oh my bad. I was looking for the 1.16.5 version and 9minecraft had it so I download it from there. I will be installing the right .jar now and I will update if it works.

**Comment by Coresixxer** [comment]
I think I found the problem. For some reason it cant load the Blessing Skins api Here is the latest log file.
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/6418945/CustomSkinLoader.log)

**Comment by ZekerZhayard** [comment]
no, why the root of BlessingSkin is http://skin.prinzeugen.net/skinlib/show/62158/ ? it should be http://skin.prinzeugen.net/ or https://skin.prin.studio/csl/
but it is empty, you may need to wait for them to refresh their CDN

**Comment by Coresixxer** [comment]
So I should not edit the root link? Do I only have to move it up the loadlist?

**Comment by ZekerZhayard** [comment]
> So I should not edit the root link? Do I only have to move it up the loadlist?

yes.
there is an alert in blessing skin main page in Chinese: 
![image](https://user-images.githubusercontent.com/41327811/116961885-17ab9900-acd7-11eb-8fe0-155bd20e04d6.png)
so you may wait a few hours for them to refresh their CDN

**Comment by Coresixxer** [comment]
Blessingskins worked kinda but it couldnt find my skin. I will try the other api's now I will start with littleskin. Here is the new log file if you are interested.
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/6419060/CustomSkinLoader.log)

**Comment by Coresixxer** [comment]
I tried it and it says No skins and cape found.
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/6419107/CustomSkinLoader.log)

**Comment by Coresixxer** [comment]
Thank you so much for your help. I figured it out. I used the Ely.By Api. Thanks for the quick response, Awesome mod btw

**Comment by Coresixxer** [comment]
So now if my friends install this mod and setup the right Api I can see their skins now right even if they are on cracked?
