### ISSUE TITLE
[优化]Mojang Usernames -> UUIDs 接口返回异常

### ISSUE THREAD

**Issue by Yukino0812** [JLChnToZ/MCCustomSkinLoader#162]
今天突然皮肤加载不出来了，群友的正版皮肤还被皮肤站覆盖掉。
一查发现是mojang的[Usernames to UUIDs API](https://wiki.vg/Mojang_API#Usernames_to_UUIDs)返回了这个：
```
{
    "error": "BadRequestException",
    "errorMessage": "Bad Request"
}
```
但是另外一个API [Username to UUID](https://wiki.vg/Mojang_API#Username_to_UUID)是能正常返回的。

个人修改了代码，在批量查询接口`MojangAPILoader#loadGameProfile()`返回为空时，使用单个查询的接口，自测在1.15.2的fabric跑了一下可以加载皮肤了。
想问一下mod后续对这方面会进行优化吗？

**Comment by ZekerZhayard** [comment]
如果可以的话，发个 PR 吧

**Comment by ZekerZhayard** [comment]
https://bugs.mojang.com/projects/WEB/issues/WEB-4457

**Comment by ZekerZhayard** [comment]
这个问题已经被 mojang 修复了

**Comment by xfl03** [comment]
Mojang已修复问题
