### ISSUE TITLE
[Compatibility] Game crashed with mod "First Person Mod" or "not enough animations"

### ISSUE THREAD

**Issue by liqa1024** [JLChnToZ/MCCustomSkinLoader#167]
## 版本
minecraft: 1.16.5, CustomSkinLoader: 14.12;  14.13-s214, forge

## 描述
和[First Person Mod](https://www.curseforge.com/minecraft/mc-mods/first-person-model)或者[Not Enough Animations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)一起使用时游戏崩溃
日志：
[minecraft-exported-logs-2021-05-21T15-43-40.log](https://github.com/xfl03/MCCustomSkinLoader/files/6520947/minecraft-exported-logs-2021-05-21T15-43-40.log)

**Comment by ZekerZhayard** [comment]
这个问题已经在 https://github.com/xfl03/MCCustomSkinLoader/pull/151 修了，请使用最新的版本
>由于发布周期的原因，从 GitHub Release 页面下载到的 CustomSkinLoader 可能已经过时，不一定能兼容最新的 Minecraft/Forge/Fabric，请访问 https://littlesk.in/csl-latest 获取最新的下载链接。

**Comment by liqa1024** [comment]
能一起安装了，十分感谢
