### ISSUE TITLE
1.10安装后无法启动游戏

### ISSUE THREAD

**Issue by g-plane** [JLChnToZ/MCCustomSkinLoader#17]
1.10使用修改核心jar文件的方法安装，然后mc就无法启动了
日志：

六月 09, 2016 11:37:58 上午 org.jackhuang.hellominecraft.launcher.Launcher main  信息: *** Hello Minecraft! Launcher 2.4.1.6 ***  六月 09, 2016 11:37:58 上午 org.jackhuang.hellominecraft.launcher.Launcher main  信息: *** Launching Game ***  [11:37:58] [Client thread/INFO]: Setting user: GPlane  [11:38:00] [Client thread/WARN]: Skipping bad option: lastServer:  [11:38:00] [Client thread/INFO]: LWJGL Version: 2.9.4  [11:38:00] [Client thread/INFO]: Reloading ResourceManager: Default  ---- Minecraft Crash Report ---- // Who set us up the TNT?  Time: 16-6-9 上午11:38 Description: Initializing game  java.lang.SecurityException: SHA-256 digest error for bxk.class      at sun.security.util.ManifestEntryVerifier.verify(Unknown Source)      at java.util.jar.JarVerifier.processEntry(Unknown Source)      at java.util.jar.JarVerifier.update(Unknown Source)      at java.util.jar.JarVerifier$VerifierStream.read(Unknown Source)      at sun.misc.Resource.getBytes(Unknown Source)      at java.net.URLClassLoader.defineClass(Unknown Source)      at java.net.URLClassLoader.access$100(Unknown Source)      at java.net.URLClassLoader$1.run(Unknown Source)      at java.net.URLClassLoader$1.run(Unknown Source)      at java.security.AccessController.doPrivileged(Native Method)      at java.net.URLClassLoader.findClass(Unknown Source)      at java.lang.ClassLoader.loadClass(Unknown Source)      at java.lang.ClassLoader.loadClass(Unknown Source)      at bcx.an(SourceFile:457)      at bcx.a(SourceFile:381)      at net.minecraft.client.main.Main.main(SourceFile:124)      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)      at java.lang.reflect.Method.invoke(Unknown Source)      at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:112)    A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Client thread Stacktrace:     at sun.security.util.ManifestEntryVerifier.verify(Unknown Source)     at java.util.jar.JarVerifier.processEntry(Unknown Source)     at java.util.jar.JarVerifier.update(Unknown Source)     at java.util.jar.JarVerifier$VerifierStream.read(Unknown Source)     at sun.misc.Resource.getBytes(Unknown Source)     at java.net.URLClassLoader.defineClass(Unknown Source)     at java.net.URLClassLoader.access$100(Unknown Source)     at java.net.URLClassLoader$1.run(Unknown Source)     at java.net.URLClassLoader$1.run(Unknown Source)     at java.security.AccessController.doPrivileged(Native Method)     at java.net.URLClassLoader.findClass(Unknown Source)     at java.lang.ClassLoader.loadClass(Unknown Source)     at java.lang.ClassLoader.loadClass(Unknown Source)     at bcx.an(SourceFile:457)  -- Initialization -- Details: Stacktrace:     at bcx.a(SourceFile:381)     at net.minecraft.client.main.Main.main(SourceFile:124)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)     at java.lang.reflect.Method.invoke(Unknown Source)     at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:112)  -- System Details -- Details:     Minecraft Version: 1.10     Operating System: Windows 7 (amd64) version 6.1     Java Version: 1.8.0_73, Oracle Corporation     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation     Memory: 119007424 bytes (113 MB) / 183500800 bytes (175 MB) up to 939524096 bytes (896 MB)     JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx896m     IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0     Launched Version: HMCL 2.4.1.6     LWJGL: 2.9.4     OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.14.4280, Intel     GL Caps: Using GL 1.3 multitexturing. Using GL 1.3 texture combiners. Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported. Shaders are available because OpenGL 2.1 is supported. VBOs are available because OpenGL 1.5 is supported.      Using VBOs: Yes     Is Modded: Probably not. Jar signature remains and client brand is untouched.     Type: Client (map_client.txt)     Resource Packs:      Current Language: 简体中文 (中国)     Profiler Position: N/A (disabled)     CPU: 4x Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz  #@!@# Game crashed! Crash report saved to: #@!@# D:\Game\Minecraft\Minecraft 1.10\.minecraft\crash-reports\crash-2016-06-09_11.38.00-client.txt

**Comment by xfl03** [comment]
没有删除核心文件中的META-INF文件夹
