### ISSUE TITLE
latest version is loading a weird skin in over my player.

### ISSUE THREAD

**Issue by githubbingitup** [JLChnToZ/MCCustomSkinLoader#172]
version: CustomSkinLoader_Fabric-14.13-s278

i have no skins uploaded on any of the sites and when using this version it loads some weird pink skin in. doesnt happen on older ones.

**Comment by akyag** [comment]
same here.. tried creating an instant of MC with just optifine and latest version of this mod. Got weird black appearance instead of the skin.

**Comment by ZekerZhayard** [comment]
can you provide your screenshots and logs (`.minecraft/CustomSkinLoader/CustomSkinLoader.log`)?
