### ISSUE TITLE
Unable to Fetch Updated Skins.

### ISSUE THREAD

**Issue by VanillaChan6571** [JLChnToZ/MCCustomSkinLoader#174]
I am using Legacy Options and set my skins to an HTTP site so I can upload them and play with my friends as they can see. The only issue I cannot find or fix is YOU HAVE TO RESTART THE GAME to fetch new skin files. 

If someone uploaded or updated their skin. Cloudflare is not caching the website as it automatically updates on refresh.

Steps I did:

Disabled Cloudflare Caching.
Messed with cacheExpiry even set it to 0 (Thinking it will automatically always get new skin on relog or rejoin)
Disable Caching 
Messed with retryTimings

The only way is to restart the game which is not useful or Wait 4-5 mins. Rejoin Server then reload resource pack by F3+T and skin gets updated. Kinda a lot of work.

**Comment by ZekerZhayard** [comment]
cc @xfl03 
i'm not sure how caches work

**Comment by ZekerZhayard** [comment]
All APIs force 90s of caching time locally:
https://github.com/xfl03/MCCustomSkinLoader/blob/dc5ecfb576ad509d4c21d4c698ecefd6f20a57cf/Common/source/customskinloader/loader/MojangAPILoader.java#L118
https://github.com/xfl03/MCCustomSkinLoader/blob/dc5ecfb576ad509d4c21d4c698ecefd6f20a57cf/Common/source/customskinloader/loader/JsonAPILoader.java#L84
https://github.com/xfl03/MCCustomSkinLoader/blob/dc5ecfb576ad509d4c21d4c698ecefd6f20a57cf/Common/source/customskinloader/loader/LegacyLoader.java#L87
https://github.com/xfl03/MCCustomSkinLoader/blob/dc5ecfb576ad509d4c21d4c698ecefd6f20a57cf/Common/source/customskinloader/loader/LegacyLoader.java#L100
https://github.com/xfl03/MCCustomSkinLoader/blob/dc5ecfb576ad509d4c21d4c698ecefd6f20a57cf/Common/source/customskinloader/loader/LegacyLoader.java#L112

Not sure what remote servers caches rules are.

**Comment by xfl03** [comment]
Please provide `.minecraft/CustomSkinLoader/CustomSkinLoader.log`

**Comment by VanillaChan6571** [comment]
> All APIs force 90s of caching time locally,
> Not sure what remote servers caches rules are.

So I use my own private server to grab them. So when I upload it using an uploader. When I refresh the browser it automatically updates. This is useful for my friends to see my skin and have them upload their skin too. 

> Please provide .minecraft/CustomSkinLoader/CustomSkinLoader.log

Here is CustomSkinLoader.log

[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/6771382/CustomSkinLoader.log)

**Comment by VanillaChan6571** [comment]
I guess what I am saying is... It requires more steps to reload other people's skins or load them. My thought of using this system I set up would be simple as using Mojang Skin System just pick the skin in the launcher and re-login to the server and updated to other people and you. But is clearly how it's coded or done is not how it works what I thought it would do.

**Comment by xfl03** [comment]
I could not find any thing about "load from cache" in the log file, each request was sent to the skin server.

**Comment by VanillaChan6571** [comment]
[MemoryLeakFix](https://github.com/fxmorin/memoryLeakFix) is not compatible with this mod which explains the Fetching New Skins were not working.

However you still need to Save & Quit, then Rejoin the world THEN F3 + T to get your new skin.
