### ISSUE TITLE
只在服务端装客户端不装 能显示皮肤吗

### ISSUE THREAD

**Issue by Holy-Fak** [JLChnToZ/MCCustomSkinLoader#176]
如题

**Comment by ZekerZhayard** [comment]
这是纯客户端 mod，安装进服务端没有任何效果或者会崩溃；
如果你要一个纯服务端插件，可以考虑：https://www.spigotmc.org/resources/skinsrestorer.2124

**Comment by Holy-Fak** [comment]
好的谢谢
