### ISSUE TITLE
对“slimefun”头颅的支持

### ISSUE THREAD

**Issue by FlyingPig278** [JLChnToZ/MCCustomSkinLoader#178]
在 #30 中的百度云链接已经失效，并且我不是很懂怎么编译东西（#31） ， 具体情况和#30是一样的
希望大佬可以弄一下对“slimefun”头颅的支持
Slimefun版本： **_Slimefun4-26_**
CSL版本：**_CustomSkinLoader_ForgeLegacy-14.13-SNAPSHOT-282_**
Minecraft客户端及服务器版本：**_1.16.5_**
谢谢大佬~

**Comment by ZekerZhayard** [comment]
我本地测试了一下并不能复现这个问题，你能提供一下 CustomSkinLoader 的日志吗？（`.minecraft/CustomSkinLoader/CustomSkinLoader.log` 和 `.minecraft/logs/debug.log`）

**Comment by FlyingPig278** [comment]
终于发现了，原来slimefun的皮肤是从mojang那里搞来的，我在配置文件里把它禁用了的。。。不好意思，麻烦了
