### ISSUE TITLE
放置头颅会导致游戏崩溃

### ISSUE THREAD

**Issue by joe-vettek** [JLChnToZ/MCCustomSkinLoader#183]
版本为CustomSkinLoader_ForgeLegacy-14.13-SN
forge为36.2.0
MC为1.16.5
日志如下：https://paste.ubuntu.com/p/3pdFdYTzNs/

**Comment by joe-vettek** [comment]
https://paste.ubuntu.com/p/GFncjJFnDz/
这是模组的输出日志，对于游戏内的头颅似乎不支持。
![U92M{}7~KBF2WO9)YTZA@OX](https://user-images.githubusercontent.com/82761814/129696941-83a9c74a-00a3-4929-8d83-f3a4b91ae267.png)

**Comment by ZekerZhayard** [comment]
CustomSkinLoader 是纯客户端 mod ，无需装进服务端；
你第二个日志里显示，你把玩家名写错了，不需要加尖括号

**Comment by joe-vettek** [comment]
非常感谢提醒，没注意这个问题。今天用自定义NPC【Taterzen】的时候又崩溃了
