### ISSUE TITLE
TLauncher support

### ISSUE THREAD

**Issue by ImUrX** [JLChnToZ/MCCustomSkinLoader#184]
Is there a way to support TLauncher's skins?

**Comment by ImUrX** [comment]
I checked and this is their api https://auth.tlauncher.org/skin/profile/texture/login/(username)

**Comment by ZekerZhayard** [comment]
A conclusion I reached last year:
TLauncher hooks `net.minecraft.client.player.AbstractClientPlayer (mojang name)` to load their skins while `net.minecraft.client.resources.SkinManager (mojang name)` is the download stream of it and which CustomSkinLoader hooks.

It is unable to fix the compatibility with TLauncher Skin Mod without specifically referencing it.

**Comment by FarOFF07** [comment]
> I checked and this is their api https://auth.tlauncher.org/skin/profile/texture/login/(username)

Is the api of Tlauncher changed bro.?
