### ISSUE TITLE
Delay when changing skin

### ISSUE THREAD

**Issue by chrnogueira06** [JLChnToZ/MCCustomSkinLoader#191]
when updating or changing the skin on elyBy, the skin does not update, and even after 24 hours after changing the skin it still does not update, I went to check the api link, and there it is updated, I tried to delete the cache, but still does not update, it regenerates the cache with the old skin

**Comment by xfl03** [comment]
Please change `forceDisableCache` to `true` in `CustomSkinLoader.json`.
