### ISSUE TITLE
最新下载地址失效了 https://littlesk.in/csl-latest

### ISSUE THREAD

**Issue by cyhhao** [JLChnToZ/MCCustomSkinLoader#192]
会自动跳转至 https://mcskin.littleservice.cn/csl-latest 之后
![image](https://user-images.githubusercontent.com/5381613/138991968-ba7ca705-6113-46ec-bfc9-3eaecad81f1e.png)

**Comment by ZekerZhayard** [comment]
现在 littlesk.in 正在申请备案，所以暂时不能访问

**Comment by z0z0r4** [comment]
那从哪里下周？

**Comment by ZekerZhayard** [comment]
> 那从哪里下周？

@z0z0r4 https://csl.littleservice.cn/latest.json

**Comment by z0z0r4** [comment]
ok

**Comment by xfl03** [comment]
国内用户也可以使用 https://3-3.dev/csl-download
