### ISSUE TITLE
CSL + Fabric Cape = 主界面加载死循环

### ISSUE THREAD

**Issue by Wudji** [JLChnToZ/MCCustomSkinLoader#198]
Fabric Cape：https://www.curseforge.com/minecraft/mc-mods/capes
日志：[latest.log](https://github.com/xfl03/MCCustomSkinLoader/files/7739544/latest.log)

**Comment by ZekerZhayard** [comment]
看了一下，是因为 Fabric Capes 和 CustomSkinLoader 都 Mixin 了相同的地方：

https://github.com/CaelTheColher/Capes/blob/ec6f38bdb62a68b8f6b074e36634c4940a483a82/src/main/java/me/cael/capes/mixins/MixinCapeFeatureRenderer.java#L13
```java
    @Redirect(method = "render", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/render/RenderLayer;getEntitySolid(Lnet/minecraft/util/Identifier;)Lnet/minecraft/client/render/RenderLayer;"))
    private RenderLayer fixCapeTransparency(Identifier texture) {
        return RenderLayer.getArmorCutoutNoCull(texture);
    }
```
https://github.com/xfl03/MCCustomSkinLoader/blob/0eaf1960bf3ab592f6a468c90beb343a50ac2ca7/Vanilla/Common/source/customskinloader/mixin/MixinLayerCape.java#L13-L22

---

大致看了一下 Fabric Capes 的功能，除了 Wynntils 其他感觉都可以通过修改 CustomSkinLoader 的配置文件实现：
```json
{
    "loadlist": [
        {
            "name": "OptiFine",
            "type": "Legacy",
            "checkPNG": true,
            "cape": "http://s.optifine.net/capes/{USERNAME}.png"
        },
        {
            "name": "LabyMod",
            "type": "Legacy",
            "checkPNG": true,
            "cape": "https://dl.labymod.net/capes/{UUID}"
        }
    ]
}
```

**Comment by Wudji** [comment]
![image](https://user-images.githubusercontent.com/93850120/146659310-e5c7fb68-392b-484a-9018-f46d287cf8cf.png)

貌似披风加载有点问题
另外把optifine放到最前面貌似会导致无法加载正版皮肤(

**Comment by ZekerZhayard** [comment]
突然忘记了，OptiFine 披风不是标准的 64*32 的披风，它的纹理展开图是经过裁剪的，需要在程序中手动扩展才行；

> 另外把optifine放到最前面貌似会导致无法加载正版皮肤(

需要把配置文件中的 `forceLoadAllTextures` 改为 `true`

**Comment by Wudji** [comment]
找了个替代品：https://www.curseforge.com/minecraft/mc-mods/of-capes
