### ISSUE TITLE
[Question / Enhancement] 1.18.1 Fabric 服务器内加载头颅可能会导致游戏崩溃

### ISSUE THREAD

**Issue by Yurinann** [JLChnToZ/MCCustomSkinLoader#199]
Minecraft 1.18.1 Fabric, Loading heads within the server may cause the game to crash.

我使用了 authlib-injector, BlessingSkin Server 并在 CustomSkinLoader 的配置文件内配置了个人皮肤站 (事实上没配置时也会崩溃)
在打开诸如 HeadDatabase 等含有头颅的菜单时，经常会导致客户端卡顿崩溃。
我查阅了部分类似此问题的 Issue，但并没有得到能够使我解决问题的方式；
于是在此处寻求帮助，想知道这个问题是否能在模组处得到解决 / 有其他的解决方式。
十分感谢。

(崩溃时并未查看到相关报错)

**Comment by ZekerZhayard** [comment]
建议上传提供 `.minecraft/logs/latest.log`
CustomSkinLoader 是纯客户端 mod，不需要装进服务端

**Comment by Yurinann** [comment]
> 建议上传提供 `.minecraft/logs/latest.log` CustomSkinLoader 是纯客户端 mod，不需要装进服务端

抱歉可能是我没讲明白，我确实只装到了客户端里，我使用的服务端是 Bungee + Paper 组合。
latest.log: https://paste.helpch.at/uminucozov.sql

**Comment by ZekerZhayard** [comment]
理论上来说早在 1.17-pre1 Mojang 就已经修复了关于头颅卡顿的问题[^1]，所以不应当会卡顿，从日志中也没有体现出 CustomSkinLoader 有大量加载皮肤的现像。
建议在游戏卡顿崩溃之后，**不要**立即重新启动游戏，而是再直接上传新的 `.minecraft/logs/latest.log`

[^1]: https://bugs.mojang.com/browse/MC-65587

**Comment by Yurinann** [comment]
我的确是这么做的：我使用了 PCL2 启动器，在游戏崩溃之后导出错误报告并将其中的 latest.log 上传。

**Comment by ZekerZhayard** [comment]
那么你的 `.minecraft` 下有没有 `hs_err_pid` 开头的文件？如果有，都上传上来看看

**Comment by Yurinann** [comment]
> 那么你的 `.minecraft` 下有没有 `hs_err_pid` 开头的文件？如果有，都上传上来看看

https://paste.helpch.at/hesiwakaze.makefile
感谢您的提醒。虽然这不是同一次测试的产物）

**Comment by Yurinann** [comment]
您好，请问是否需要我提供更多信息？我很乐意。这个问题在我团队的许多成员身上出现。由于我现在无法保证这是否是服务器/客户端其他模组导致的问题，我会在之后进一步进行测试。

**Comment by ZekerZhayard** [comment]
这个问题非常玄学，我也不知道是否属于 CustomSkinLoader 的问题，但是仅从日志上来看与 CustomSkinLoader 关系并不大

**Comment by Yurinann** [comment]
> 这个问题非常玄学，我也不知道是否属于 CustomSkinLoader 的问题，但是仅从日志上来看与 CustomSkinLoader 关系并不大

是的，我也这么认为。我来此处提交的原因是因为我查看到了 #79 及其相关内容，但正如您说的，在 1.17-pre1 Mojang 已经修复了关于头颅卡顿的问题，所以我现在也不太清楚了（

**Comment by xfl03** [comment]
注意到`dev.tr7zw.skinlayers.SkinUtil.setup3dLayers`，能否删了看看

**Comment by Yurinann** [comment]
> 注意到`dev.tr7zw.skinlayers.SkinUtil.setup3dLayers`，能否删了看看

由于 Issue 时间较久，目前已经脱离原有测试环境，我会找时间还原环境并进行尝试。

**Comment by xfl03** [comment]
> > 注意到`dev.tr7zw.skinlayers.SkinUtil.setup3dLayers`，能否删了看看
> 
> 由于 Issue 时间较久，目前已经脱离原有测试环境，我会找时间还原环境并进行尝试。

那新版本（1.19.3）还有类似的问题吗，如果没有的话我感觉可以关issue了

**Comment by Yurinann** [comment]
> > > 注意到`dev.tr7zw.skinlayers.SkinUtil.setup3dLayers`，能否删了看看
> > 
> > 
> > 由于 Issue 时间较久，目前已经脱离原有测试环境，我会找时间还原环境并进行尝试。
> 
> 那新版本（1.19.3）还有类似的问题吗，如果没有的话我感觉可以关issue了

我尽快去测试一下。
(相关链接: https://github.com/tr7zw/3d-Skin-Layers)

**Comment by Yurinann** [comment]
最新版经目前测试不存在此问题，头颅皮肤会顺序加载。
感谢您对问题的持续关注。
