### ISSUE TITLE
Mavenlize please?

### ISSUE THREAD

**Issue by lifehome** [JLChnToZ/MCCustomSkinLoader#2]
Is it possible for maven this project?
cuz it would be better if this could be jenkin-automated.

**Comment by xfl03** [comment]
i am sorry this project cannot be compiled by maven automatic, because of the copyright of minecraft.

**Comment by xfl03** [comment]
Thanks for your advice.
Recently, this project have been being built automatically by jenkin and gradle.
Build server https://ci.infstudio.net/job/CustomSkinLoader/
