### ISSUE TITLE
话说作者大大能不能修一下和飞轮的冲突啊……机械动力玩家表示很难受

### ISSUE THREAD

**Issue by foyue5666** [JLChnToZ/MCCustomSkinLoader#202]

**Comment by ZekerZhayard** [comment]
forge 早就有 1.18 版本支持了啊
https://www.curseforge.com/minecraft/mc-mods/customskinloader/files/3559388

**Comment by foyue5666** [comment]
o……curseforge有了啊……我curseforge加载不出来，看releases里面没有，以为没有呢……能不能麻烦给个网盘链接啥的

**Comment by ZekerZhayard** [comment]
我们不在 GitHub 发非 release 版本，我们在 Modrinth 也有发布
https://cdn.modrinth.com/data/idMHQ4n2/versions/14.13-SNAPSHOT-309-Forge.Active/CustomSkinLoader_ForgeActive-14.13-SNAPSHOT-309.jar

项目地址 https://modrinth.com/mod/customskinloader

**Comment by foyue5666** [comment]
好的知道了，感谢大大

**Comment by ZekerZhayard** [comment]
@foyue5666 和 Flywheel 的冲突是 forge 自己的 bug，你升级 forge 就行

新的问题新开一个 issue，旧的 issue 解决之后直接关闭

**Comment by foyue5666** [comment]
好的大大，下次注意
