### ISSUE TITLE
question about json data from api

### ISSUE THREAD

**Issue by SeasonPhan** [JLChnToZ/MCCustomSkinLoader#204]
It has both cape and elytra infomation, does this mean CustomSkinLoader mod can display seperate texture for elytra and cape in-game? 
i tried but it only display one texture with elytra texture having highest priority

**Comment by ZekerZhayard** [comment]
The elytra texture doesn't affect the cape texture, but the cape texture affects the elytra texture, so the elytra has a higher priority than the cape - this is vanilla feature, CustomSkinLoader doesn't intervene.
Elytra was added in a snapshot of Minecraft 1.9. At that time, elytra was still a separate texture, not bound to the cape. This feature has been retained to this day.

**Comment by SeasonPhan** [comment]
is elytra still a seperate texture in 1.18? im using a skin server from [https://github.com/yotsubar/CustomSkinLoaderAPIServer](url) and look like changing only the elytra also make the cape texture changed

**Comment by ZekerZhayard** [comment]
Can you provide the logs of the CustomSkinLoader when you upload the elytra separately and enter the game?  It's the `CustomSkinLoader.log` located in the `.minecraft/CustomSkinLoader` directory.

**Comment by SeasonPhan** [comment]
sure
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/8115280/CustomSkinLoader.log)

**Comment by ZekerZhayard** [comment]
it's a bug of CustomSkinLoader. Thanks for reporting!

**Comment by SeasonPhan** [comment]
no problem, im happy to help ^^

**Comment by ZekerZhayard** [comment]
this issue should be fixed in the latest build

Forge
1.7.10 ~ 1.16.5: https://csl.littleservice.cn/mods/CustomSkinLoader_ForgeLegacy-14.13-SNAPSHOT-314.jar
1.17+: https://csl.littleservice.cn/mods/CustomSkinLoader_ForgeActive-14.13-SNAPSHOT-314.jar

Fabric https://csl.littleservice.cn/mods/CustomSkinLoader_Fabric-14.13-SNAPSHOT-314.jar
