### ISSUE TITLE
[1.16.5 Forge] Baby Zombies on server will render as full sized zombie instead.

### ISSUE THREAD

**Issue by Colin-J-Wood** [JLChnToZ/MCCustomSkinLoader#205]
self explanatory.  could be related to optifine messing with the IsBaby tag (might result in all nbt tags being read incorrectly in general)

Forge 36.2.20
Minecraft 1.16.5
Custom Skin Loader: 14.13-SNAPSHOT314

Other Mods:
Optifine G8
Kaleidio's Battle Pack 4.3.0 dev branch (4.2.10 available on curseforge for testing sake)

Randomly capable of reproducing the issue without any other mods however.

**Comment by Colin-J-Wood** [comment]
note that downgrading to snapshot313 fixes the issue

**Comment by ZekerZhayard** [comment]
CustomSkinLoader is a client side mod and nothing doing on server side. CustomSkinLoader also doesn't have any code related to zombie rendering. Please test to make sure the issue is caused by CustomSkinLoader by just installing this mod or removing this mod from the modpack.

**Comment by Colin-J-Wood** [comment]
I did exactly that and that is why I'm here.

**Comment by Colin-J-Wood** [comment]
note that the minecraft system *does* have a ton of things to deal with nbt on the client side, mostly to deal with choosing which model the entity should render.  in the case of zombies, if the client is reading IsBaby:0 but the server reads IsBaby:1, it will swap the model like experienced but behave, sound, and have hitboxes of a baby (the only thing behaving wrongly is which model is rendering visually)

reference as proof, and some insight on how the packets handle them:
https://stackoverflow.com/questions/46757423/nbt-loading-on-client-vs-server-side

**Comment by Colin-J-Wood** [comment]
clarifications have been made to my comments.  I suspect the recent changes noted here have made issue:
![image](https://user-images.githubusercontent.com/91890547/155894435-e5f3d3e5-099b-4205-a3e7-7954835c62ba.png)

**Comment by Colin-J-Wood** [comment]
note that this only happens when playing on a dedicated server, singleplayer is not affected.  should have clarified that better as well.  maybe it's a simple issue with wrong side methods being used?

**Comment by ZekerZhayard** [comment]
I can't reproduce this issue. I used Kaleidio's Battle Pack 4.2.10 downloaded from CusrForge and entered the corresponding dedicate server. Use the `/summon minecraft:zombie ~ ~ ~ {IsBaby:1}` command to spawn baby zombies and everything works fine. 
![2022-02-28_02 50 02](https://user-images.githubusercontent.com/41327811/155895600-ed2b44a9-34ab-4791-ad1f-a4d568dce0c7.png)

**Comment by Colin-J-Wood** [comment]
try playing with the modpack with Optifine installed.  If not, vivecraft nonvr.

**Comment by ZekerZhayard** [comment]
I'm also tested with optifine, nothing different

**Comment by Colin-J-Wood** [comment]
must be random occurrence then, probably cleared out after restarting when I had removed your mod.

**Comment by Colin-J-Wood** [comment]
I'll keep this tracker open until I can verify it;

1. still happens on the 4.3.0 beta branch
2. is custom skin loader at fault

in the case of the latter I will still keep it open and post the mods it is colliding with.

no clue how long that will take considering such randomness to the circumstances.

**Comment by ZekerZhayard** [comment]
If necessary, share the save that reproduces the issue, and record a video of the issue.

**Comment by NighthowlerStudios** [comment]
I cannot do either as I tend to delete worlds between tests for drive space sake.  I will however do both of those if it arises again

**Comment by NighthowlerStudios** [comment]
note that kbp 4.3.0 dev branch has quite a few mod differences, but I thought they wouldn't have been major enough to mention.  I will provide a list next time.

**Comment by Colin-J-Wood** [comment]
seemingly the issue was down to world corruption when mods were changed between the same save.  Closing issue.
