### ISSUE TITLE
[Bug] capes doesn't work

### ISSUE THREAD

**Issue by JPAM937alt** [JLChnToZ/MCCustomSkinLoader#209]
I'm using the mod in the latest version with minecraft version 1.12.2 but littleskins capes don't load

**Comment by ZekerZhayard** [comment]
provide your logs:
- .minecraft/logs/latest.log
- .minecraft/CustomSkinLoader/CustomSkinLoader.log
- .minecraft/logs/debug.log (may not exist)

**Comment by JPAM937alt** [comment]
I think this was a problem of LittleSkins itself because a few days later the capes started working again
