### ISSUE TITLE
[Question] How can I load a skin onto a Player Entity?

### ISSUE THREAD

**Issue by CodedRedGIT** [JLChnToZ/MCCustomSkinLoader#212]
Is there any API for my mod to communicate with so that I could load a custom HD texture onto my dummy Player Entity? Thank you!

**Comment by ZekerZhayard** [comment]
We support loading player skins in a similar way to the Mojang API. You can actively add a `GameProfile` for a given player in the spigot plugin, like you said in this video https://www.youtube.com/watch?v=vswQvReadrc.
Unlike the Mojang API, the base64 parsed address in the `texture` attribute can point to any address of legal png image, not just Mojang's addresses, so you can add the address to the HD skin here.
