### ISSUE TITLE
issue with caches

### ISSUE THREAD

**Issue by ImUrX** [JLChnToZ/MCCustomSkinLoader#213]
skin caches that are outside the Minecraft instance's folder make the game keep loading old skins, MultiMC stores it on ``MultiMC/assets/skins`` and TLauncher keeps it on ``.tlauncher/cache/`` for example

**Comment by VanillaChan6571** [comment]
Similar Issue to #174

**Comment by ImUrX** [comment]
yeah your case seems to be with Twitch/CurseForge launcher, i havent tried but have you checked if changing in ``CustomSkinLoader.json`` the ``"enableCacheAutoClean"`` setting to ``true`` makes it work

**Comment by ZekerZhayard** [comment]
I don't think these two issues describe the same problem. This issue is caused by premature initialization of certain classes which prevents the assets/skins directory from being cleaned up. This has been fixed in my local, and I will submit the fix after waiting for 1.19.1 to be released.

**Comment by ImUrX** [comment]
😭 seems we will have to wait
btw, MAKE A PR NEXT TIME WHEN YOU HAVE THE FIX DONE SO I CAN BUILD IT AAAAAAAAAAAAAAAAA (and everyone else knows its being fixed instead of empty silence)

**Comment by VanillaChan6571** [comment]
> 😭 seems we will have to wait btw, MAKE A PR NEXT TIME WHEN YOU HAVE THE FIX DONE SO I CAN BUILD IT AAAAAAAAAAAAAAAAA (and everyone else knows its being fixed instead of empty silence)

No, the sad part is @xfl03 knew this and has done nothing since 1.16.x

**Comment by ImUrX** [comment]
Your issue and this one are apparently different, I'm sad that there was no info on the issue already being fixed. Imagine if I start fixing this when I later discover that someone already fixed it.
I do hope your issue gets fixed. :/
