### ISSUE TITLE
Local skin issue

### ISSUE THREAD

**Issue by mqtrx** [JLChnToZ/MCCustomSkinLoader#214]
![image](https://user-images.githubusercontent.com/94565446/178121987-03e8930c-1656-4e54-a8d2-9a9d63396b19.png)
These are npc's in the screenshot by the way, is this a bug or a me issue?

I did everything correctly but I don't know why this happens.

**Comment by ZekerZhayard** [comment]
please provide the log. it's `CustomSkinLoader.log` in `.minecraft/CustomSkinLoader`

**Comment by mqtrx** [comment]
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/9077952/CustomSkinLoader.log)

**Comment by ZekerZhayard** [comment]
It seems that your configuration file is wrong. The `{USERNAME}` in `LocalSkin` is a placeholder, which is automatically replaced by the required username by CustomSkinLoader, and does not need to be modified manually.
