### ISSUE TITLE
Optifine cape overwrites Local cape

### ISSUE THREAD

**Issue by mqtrx** [JLChnToZ/MCCustomSkinLoader#215]
https://user-images.githubusercontent.com/94565446/178122681-73db5439-82a2-45c0-a36f-090b8061389d.mp4
![mqtrx](https://user-images.githubusercontent.com/94565446/178122703-2a472263-93a7-4edc-812c-b03d04eee064.png)

The image above is the cape I wanna use but can't, cause of this issue

**Comment by ZekerZhayard** [comment]
OptiFine patched the upstream code, resulting in OptiFine capes always taking precedence over vanilla and CustomSkinLoader capes. We also have no plans to fix this
