### ISSUE TITLE
Salwyrr support

### ISSUE THREAD

**Issue by Byllfighter** [JLChnToZ/MCCustomSkinLoader#219]
How can I make Salwyrr skins support?

**Comment by ZekerZhayard** [comment]
Can Salwyrr skins see each other in multiplayer?

**Comment by Byllfighter** [comment]
my friend, that plays with it says yes

**Comment by xfl03** [comment]
If you can provide the skin getting API of Salwyrr, we can support it.

**Comment by xfl03** [comment]
Sorry, it is not an open API, we can't do that.
