### ISSUE TITLE
seus光影及光追光影下仍然无法修复透明皮肤问题

### ISSUE THREAD

**Issue by ShenxPresent** [JLChnToZ/MCCustomSkinLoader#221]
seus光影及光追光影下仍然无法修复透明皮肤问题，看起来似乎是在光影渲染下修改了渲染方式导致失效了

**Comment by ZekerZhayard** [comment]
你用的哪个版本的 Minecraft，哪个版本的 forge/fabric，哪个版本的 optifine/iris，哪个版本的 SEUS

我在以下环境下测试透明皮肤都没有问题
>- Minecraft 1.16.5
>- Fabric Loader 0.14.8
>- OptiFabric 1.13.10
>- OptiFine 1.16.5 HD U G8
>- CustomSkinLoader 14.14-SNAPSHOT-343
>- SEUS PTGI HRR 3

>- Minecraft 1.18.2
>- Fabric Loader 0.14.8
>- OptiFabric 1.13.10
>- OptiFine 1.18.2 HD U H7
>- CustomSkinLoader 14.14-SNAPSHOT-343
>- SEUS PTGI HRR 3

>- Minecraft 1.16.5
>- Fabric Loader 0.14.8
>- Fabric API 0.42.0+1.16
>- Sodium mc1.16.5 0.2.0+build.4
>- Iris Shaders mc1.16.5 1.2.6
>- CustomSkinLoader 14.14-SNAPSHOT-343
>- SEUS PTGI HRR 3

>- Minecraft 1.18.2
>- Fabric Loader 0.14.8
>- Fabric API 0.58.0+1.18.2
>- Sodium mc1.18.2 0.4.1+build.15
>- Iris Shaders mc1.18.2 1.2.6
>- CustomSkinLoader 14.14-SNAPSHOT-343
>- SEUS PTGI HRR 3

**Comment by ShenxPresent** [comment]
我在
Minecraft 1.16.5，
forge 36.2.33 
optfine G8
CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-343
SEUS PTGI HRR 2
NostalgiaVX_P7c_2022-6-27_23.35
ITT3.0
下都有问题

**Comment by ZekerZhayard** [comment]
![2022-08-12_21 08 32](https://user-images.githubusercontent.com/41327811/184360338-0db5e6a2-fb67-4b39-913f-93119e02d784.png)

我用 ITT3.0 没发现有什么问题，
你现在透明皮肤渲染出来是啥样的？用了哪个皮肤站？有些皮肤站会把上传的皮肤纹理的 alpha 通道删除

**Comment by ShenxPresent** [comment]
![image](https://user-images.githubusercontent.com/53565917/184360831-4ebbbd89-5ce1-4c1d-89b5-e3bbecb14641.png)
![image](https://user-images.githubusercontent.com/53565917/184360865-f1f4d367-3b5f-41c9-9e04-99e66161fe2d.png)
官方皮肤，用户名ShenxPresent

**Comment by ZekerZhayard** [comment]
你这皮肤压根就不带透明部分
http://textures.minecraft.net/texture/e308e2edb79293ce5d86bded974963f1321759ff718d3babccea647c17bee8cd
![1](https://user-images.githubusercontent.com/41327811/184362082-20e75888-aa54-4131-bf6b-9032a9c1f8a3.png)

**Comment by ShenxPresent** [comment]
在bsl和背包里渲染都是正常的，应该是有透明部分的，可以看我刚刚发的截图
![image](https://user-images.githubusercontent.com/53565917/184362469-fe256b33-b5d5-44f9-94e6-feb9a05fd619.png)

**Comment by ZekerZhayard** [comment]
简单研究了一下，应该就是这些光影没开 alpha blending，你应该向这些光影作者反馈，CSL 方面应该是无能为力的

**Comment by ShenxPresent** [comment]
那为什么你这边的环境下itt3可以，而我不行呢

**Comment by ZekerZhayard** [comment]
因为全透明像素是不需要 alpha blending 的，我能复现你的半透明像素纹理的问题

**Comment by ShenxPresent** [comment]
了解了，感谢
