### ISSUE TITLE
OptiFine Capes works not correctly

### ISSUE THREAD

**Issue by Byllfighter** [JLChnToZ/MCCustomSkinLoader#222]
```
    {
      "name": "OptiFine",
      "type": "Legacy",
      "checkPNG": true,
      "cape": "https://optifine.net/capes/{USERNAME}.png"
    }
```
In preview `OptiFineCape` account: https://namemc.com/profile/OptiFineCape.1
![image](https://optifine.net/capes/OptiFineCape.png)
![image](https://user-images.githubusercontent.com/60580992/184498410-e2b4afd9-7f3d-4a7f-9751-85a85181495d.png)

**Comment by ZekerZhayard** [comment]
The size of the OptiFine Cape is not the standard size of the Minecraft cape (an integer multiple of 64:32), so additional logic is required to complete the OptiFine Cape size to the standard size.

**Comment by Byllfighter** [comment]
Can i do it in `loadlist`?

**Comment by ZekerZhayard** [comment]
you can but you need to write some Java code

**Comment by Byllfighter** [comment]
i dont know java

**Comment by 8MiYile** [comment]
@ZekerZhayard @xfl03 
https://github.com/CaelTheColher/Capes
找到了一个插件 但是是Fabric的 希望你们可以参考一下（I found a plugin, but it's for Fabric. I hope you can refer to it.）

**Comment by xfl03** [comment]
https://github.com/xfl03/MCCustomSkinLoader/commit/84072c62f37a4f3128a90a319a2eeb3fbf6aa45a

## Download develop build
- Fabric https://csl.littleservice.cn/mods/CustomSkinLoader_Fabric-14.16-SNAPSHOT-21.jar
- Forge 1.8~1.16.5 https://csl.littleservice.cn/mods/CustomSkinLoader_ForgeLegacy-14.16-SNAPSHOT-21.jar
- Forge 1.17.1~1.19.3 https://csl.littleservice.cn/mods/CustomSkinLoader_ForgeActive-14.16-SNAPSHOT-21.jar

**Comment by 8MiYile** [comment]
光速更新（草）
