### ISSUE TITLE
Question about the mod

### ISSUE THREAD

**Issue by TathanDev** [JLChnToZ/MCCustomSkinLoader#223]
Hey^^
I have a question about this mod : on the curseforge, it is written that the mod is only a client. But if I want to use a different skin server, I have to put it on my server too?

Thanks

**Comment by xfl03** [comment]
Skin server is not together with game server.
If I want to use a different skin server, please chance the config in client which located in `.minecraft/CustomSkinLoader/CustomSkinLoader.json`.

**Comment by TathanDev** [comment]
ok thanks^^
