### ISSUE TITLE
1.19Fabric自行配置的皮肤站被异常清除

### ISSUE THREAD

**Issue by matrix-a11y** [JLChnToZ/MCCustomSkinLoader#224]
我在配置文件里配置了自己的皮肤站，测试发现在游戏内为正确加载皮肤，然后我去检查配置文件，发现我自己配置的部分被清除了
这怎么解决

**Comment by ZekerZhayard** [comment]
发一下你之前修改后的配置文件看看？

**Comment by xfl03** [comment]
应该是配置文件格式不正确（不是正确的json格式），被还原了，如果需要的话可以发上来帮你看看

**Comment by 8MiYile** [comment]
修改保存后，要去bejson网站检查一下你的JSON格式是否正确
推荐使用Visual Studio Code或者这类程序，在编辑的时候查看JSON格式是否正确
