### ISSUE TITLE
Support The CurseForge Launcher

### ISSUE THREAD

**Issue by PolyframeX** [JLChnToZ/MCCustomSkinLoader#226]
This would allow a lot more users to use your mod.

**Comment by ZekerZhayard** [comment]
why doesn't this mod support cf launcher? it shouldn't be defferent from ohter launcher

**Comment by PolyframeX** [comment]
Well for some reason no configuration files generate at all. and when I make one for myself I have no idea where to put the said configuration file. It shouldn't be the .minecraft folder because the mod is installed in an entirely diffrent directory, nowhere located in .minecraft, The mod Automaticlly installs in C:\Users\<NAME>\curseforge\minecraft\instances\<COLLECTION NAME>\mods\ instead where the versions are located.

**Comment by ZekerZhayard** [comment]
the `CustomSkinLoader` folder will be always generated in current working directory when you first join in a world, it should be the same as where `mods` folder at.

**Comment by PolyframeX** [comment]
I did not know that, a folder was never generated in the first place.

(I'll check if the mod install got corrupted, that happens a lot for some reason)

**Comment by ZekerZhayard** [comment]
can you provide your game logs? it should
be named `latest.log` which in `logs` folder

**Comment by PolyframeX** [comment]
It was a corrupted install, thanks anyways.

If you can help me out with one last thing, I can't find an API that actually works with HD Skins/Capes. All of them either are for china users, or just don't work.

**Comment by ZekerZhayard** [comment]
How did you set HD skin? If you can provide more operational details and logs will have more help.

**Comment by PolyframeX** [comment]
Well on the API I got the skins on the website, I just can't apply them, because I require to connect my Mojang account, however when I click on this button, it just refreshes the page. I was using LittleSkin

**Comment by ZekerZhayard** [comment]
LittleSkin's Minecraft account verification is temporarily unavailable.

**Comment by PolyframeX** [comment]
Oh, well that makes sense, how long do you think it'll take for it to be back up?

**Comment by gxres042** [comment]
> Oh, well that makes sense, how long do you think it'll take for it to be back up?

Wait for LittleSkin administrators to announce

**Comment by PolyframeX** [comment]
Okay, well thanks for the help, I really appreciate it!
