### ISSUE TITLE
How to use other player's skin?

### ISSUE THREAD

**Issue by FlameFire26** [JLChnToZ/MCCustomSkinLoader#239]
I want to play on a server, but it hasn't CSL, so I want to use specific Mojang player's skin to show. But that means I need to change my name to use that. Can I make it by edit CustomSkinLoader.json while using my original name?

If not, could you add it?

It might like this: In the file, 'Mojang' should have 'playername'

**Comment by xfl03** [comment]
Please download that skin and upload to your account.  
The link of the skin can be found in `.minecraft/CustomSkinLoader/CustomSkinLoader.log`.

**Comment by 8MiYile** [comment]
and please reopen new issue
thanks
