### ISSUE TITLE
[Suggestion/Log] mclo.gs未适配CustomSkinLoader的问题

### ISSUE THREAD

**Issue by 8MiYile** [JLChnToZ/MCCustomSkinLoader#240]
### 描述一下

本反馈先挂起，直到这个log页面能解析出信息，再去关闭
https://mclo.gs/Zyny8V7
啊对了 如果你们能发个log格式那是最好不过的了
@xfl03 
Issue: https://github.com/aternosorg/mclogs/issues/50

### 在提交反馈或建议之前,请先确认...

- [X] 你要提交的反馈或者建议不存在于本模组的最新开发版下. 

- [X] 以及在issues或者Wiki内搜索过, 并且无结果

**Comment by 8MiYile** [comment]
主要差的是格式 比如WARM ERR这些的 因为我的这份日志里头没有这些内容 所以他们要标记颜色也不好标记
@xfl03

**Comment by xfl03** [comment]
> 主要差的是格式 比如WARM ERR这些的 因为我的这份日志里头没有这些内容 所以他们要标记颜色也不好标记 @xfl03

能传纯文本就行

**Comment by 8MiYile** [comment]
@xfl03 
看看链接 刚发现有更新
![image](https://user-images.githubusercontent.com/25455400/213760467-53d5ee19-3e08-4f25-99c9-a44044f91120.png)
