### ISSUE TITLE
Skin not displaying

### ISSUE THREAD

**Issue by BananaBlu77** [JLChnToZ/MCCustomSkinLoader#241]
### Describe the bug

When joining world (both single player and server) skin isn't displaying. Tried with LittleSkin and LocalSkin.

### Steps to reproduce

```bash
1) Join a world
2) My skin isn't displaying, instead I have the Alex skin.
```

### Link to CustomSkinLoader.log if applicable

https://mclo.gs/TMcfK3w

### Mod Version

Tried with 14.15-SNAPSHOT-353 and 14.15.1

### Minecraft Version

1.19.2

### Mod Loader

Forge

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ZekerZhayard** [comment]
can you provide `.minecraft\logs\latest.log` ?
the log of CustomSkinLoader looks like everything is ok, maybe `latest.log` can provide more information.

**Comment by BananaBlu77** [comment]
latest.log
https://mclo.gs/GbeQY34

**Comment by 8MiYile** [comment]
@ZekerZhayard 我需要修改工单模板吗？

**Comment by ZekerZhayard** [comment]
@8MiYile 需要，包括 latest.log 和 debug.log（forge 1.12.2+）和 fml-client-latest.log（forge-1.12.2-）

**Comment by BananaBlu77** [comment]
Posting all the logs together, in case you need more informations
CustomSkinLoader.log - https://mclo.gs/15xJoBj
latest.log - https://mclo.gs/FgRAWSM
debug.log - https://mclo.gs/WjuOrv2

**Comment by ZekerZhayard** [comment]
> Posting all the logs together, in case you need more informations CustomSkinLoader.log - https://mclo.gs/15xJoBj latest.log - https://mclo.gs/FgRAWSM debug.log - https://mclo.gs/WjuOrv2

这个日志里没有显示任何报错，看起来一切正常，所以我也不知道问题出在哪里

**Comment by BananaBlu77** [comment]
So where could the mistake be? Are there any other logs that can be useful?

**Comment by 8MiYile** [comment]
One moment, this issue is three weeks old, 
can you please provide a list of your Mods?
Because if the Mod loader is Forge, I feel that other modules of Forge have problems, which indirectly or directly affects the work of CustomSkinLoader

**Comment by BananaBlu77** [comment]
Sure, here it is ("dir" command output in the mods folder):

```
23/01/2023`  18:08           527.755 additional_lights-1.19-2.1.5.jar
18/01/2023  21:02        77.110.785 AmbientSounds_FORGE_v5.2.13_mc1.19.2.jar
19/01/2023  17:03         9.916.886 appliedenergistics2-forge-12.9.2.jar
31/01/2023  18:13           545.069 architectury-6.4.62-forge.jar
23/01/2023  18:14           623.779 balm-4.5.3.jar
31/01/2023  18:00         2.166.478 betteranimalsplus-1.19.2-11.0.10-forge.jar
18/01/2023  21:03           159.591 BiomeParticleWeather-v4.0.0-1.19-Forge.jar
18/01/2023  21:24         2.213.494 cfm-7.0.0-pre34-1.19.jar
18/01/2023  21:24         1.659.634 cgm-1.3.3-1.19.2.jar
18/01/2023  20:59        15.016.746 create-1.19.2-0.5.0.h.jar
18/01/2023  21:04           917.024 CreativeCore_FORGE_v2.9.3_mc1.19.2.jar
22/01/2023  17:54           132.850 CustomSkinLoader_ForgeActive-14.15-SNAPSHOT-353.jar
20/01/2023  18:46           493.789 dragon-mounts-1.19.x-1.1.4a (1).jar
31/01/2023  18:11         2.701.111 FarmersDelight-1.19-1.2.0.jar
18/01/2023  21:07           110.826 framework-0.4.2-1.19.2.jar
18/01/2023  21:07         2.512.824 handcrafted-forge-1.19.2-2.0.2.jar
23/01/2023  18:07         1.034.464 horse_colors-1.19.2-11.1.jar
22/01/2023  14:00        10.622.742 ImmersiveEngineering-1.19.2-9.1.0-156.jar
22/01/2023  17:49         1.085.313 jei-1.19.2-forge-11.5.2.1007.jar
31/01/2023  18:14           947.498 LibX-1.19.2-4.2.5.jar
31/01/2023  17:56         2.034.912 lightmanscurrency-1.19.2-2.0.1.0.jar
31/01/2023  18:11         3.942.453 mahoutsukai-1.19.2-v1.34.38.jar
31/01/2023  18:01        12.165.627 Mekanism-1.19.2-10.3.6.475.jar
18/01/2023  21:20         1.116.377 modular-routers-1.19.2-10.2.0-3.jar
23/01/2023  18:14           754.014 moonlight-1.19.2-2.1.30-forge.jar
31/01/2023  17:56           186.324 More-Vanilla-Tools-Mod-Forge-1.19.2.jar
31/01/2023  18:11           346.037 NethersDelight-1.19-3.0.jar
18/01/2023  21:05         1.886.544 oculus-mc1.19.2-1.2.8a.jar
23/01/2023  18:08            37.147 ordinarycoins-1.0.2-forge.jar
18/01/2023  21:25           538.939 Platforms-Mod-Forge-1.19.2.jar
18/01/2023  21:19           228.493 resourcefullib-forge-1.19.2-1.1.19.jar
18/01/2023  21:06         1.369.128 rubidium-0.6.2.jar
18/01/2023  21:06           203.480 RubidiumExtra-1.19.2-0.4.11.44.jar
18/01/2023  21:25           455.922 ShetiPhianCore-Forge-1.19.2.jar
23/01/2023  18:07           580.748 StorageDrawers-1.19-11.1.2.jar
31/01/2023  18:33           215.787 summoningrituals-1.19.2-2.0.3.jar
23/01/2023  18:08        14.423.616 supplementaries-1.19.2-2.2.41.jar
19/01/2023  17:24           194.768 TextruesRubidiumOptions-1.0.4-mc1.19.2.jar
18/01/2023  21:26           353.637 tinyredstone-1.19.2-4.1.2.jar
23/01/2023  18:07           365.792 waystones-forge-1.19-11.1.0.jar
24/01/2023  18:33         5.650.155 worldedit-mod-7.2.12.jar
21/01/2023  12:27         3.326.192 [1.19.2]+SecurityCraft+v1.9.4.jar
```

My friends have the same mods (except for rubidium, rubidium-extra, texture-rubidium-option and oculus), and they see the skins.

**Comment by 8MiYile** [comment]
maybe this mod `texture-rubidium-option`

**Comment by 8MiYile** [comment]
Why would you want to use these mods?
1. rubidium (forge's sodium)
2. rubidium-extra
3. texture-rubidium-option
4. oculus (forge's iris)

I think OptiFine should be more suitable for your environment, after all, you are using forge mod loader it
Or you can try to remove the first 3 mods and try again to see if they load
@BananaBlu77

**Comment by BananaBlu77** [comment]
Only wanted to try out some graphical/optimization mods. I can't use OptiFine because game crashes, so I need oculus to play with shaders, but oculus requires rubidium. I've tried to remove those four mods and still no skin displaying.

**Comment by BananaBlu77** [comment]
Solved, it was a compatibility issue due to the skin system of SKLauncher (yes, I was using SKLauncher). Disabling it (turn on compatibility mode) solved the issue.

**Comment by 8MiYile** [comment]
标记为乌龙事件 与SKLauncher的皮肤系统冲突

**Comment by 8MiYile** [comment]
@BananaBlu77 
Thank you very much for the solution
Since our module does not take into account that game launchers released in other countries will have an impact on the functionality of our mod
We would like to express our great appreciation
