### ISSUE TITLE
Move Config Location

### ISSUE THREAD

**Issue by PolyframeX** [JLChnToZ/MCCustomSkinLoader#245]
### Describe the feature

Move The Configuration Files Into The Default Config Folder. This Would Make Managing Modpacks Or Just A Lot Of Mods Much Easier.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 8MiYile** [comment]
Move from `.minecraft/CustomSkinLoader` to `.minecraft/config/CustomSkinLoader`?

**Comment by PolyframeX** [comment]
Yeah

**Comment by 8MiYile** [comment]
@xfl03 看一下吧

**Comment by xfl03** [comment]
We have a lot of files in `.minecraft/CustomSkinLoader`, not only config file.
