### ISSUE TITLE
Please update to 1.19.4

### ISSUE THREAD

**Issue by CCjun6** [JLChnToZ/MCCustomSkinLoader#247]
### Describe the feature

I really like this mod and have been using it for years
So please update when you have time
I can sponsor if needed

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 8MiYile** [comment]
https://github.com/xfl03/MCCustomSkinLoader/actions/runs/4645566728
You can download it here, I saw that there is a version 1.19.4 support
（Tip: If you don't see a supported version in the description, you can go to the Actions page, select the last build, download the file inside, and find out if there is a corresponding version!）

**Comment by 8MiYile** [comment]
@xfl03 这个工单标记为已解决

**Comment by 8MiYile** [comment]
@CCjun6 
Sometimes our staff will be busy, but we will be late in adapting new versions of the game, but we will not fail to update, usually after the release of the new version can be a few days to see if there is a corresponding version of the game within the new build of Action
（Tip: Action area is generally Beta, if there is a crash situation, or some functions are not working properly, you can choose Report Bug to submit Log）

**Comment by CCjun6** [comment]
OK thank you very much for the update

**Comment by 8MiYile** [comment]
Okay, please remember to close the issue and select Resolved
