### ISSUE TITLE
[Bug] Mod Seens Has a Malware on Anti-virus Weirdly

### ISSUE THREAD

**Issue by Vylesh** [JLChnToZ/MCCustomSkinLoader#248]
### Describe the bug

I have a Lots of mods, modpack on my PC but I was Scanned my pc with My Anti-virus Program (Kaspersky I'm using) Program is Says Weirdly This mod is a Susupicious. in short idk what am i need say more...

![resim](https://user-images.githubusercontent.com/83465565/230653347-cd3580e5-e27d-4aa6-a04c-12da956a82eb.png)

### Steps to reproduce

```bash
1. Download CustomSkinLoader_Fabric-14.13-SNAPSHOT-313.jar
2. Run Vİrus Scan With Anti-Virus
3. Result
```

### Link to CustomSkinLoader.log if applicable

efekaanklc@yahoo.com

### Link to latest.log if applicable

efekaanklc@yahoo.com

### [Only Forge User] Link to debug.log (=>1.12.2) or fml-client-latest.log (=<1.12.2)  if applicable

efekaanklc@yahoo.com

### Mod Version

14.13

### Minecraft Version

1.18.X

### Mod Loader

Fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Vylesh** [comment]
I Sended This here bcuz i'm getted this type bug First time ....

**Comment by 8MiYile** [comment]
Kaspersky Antivirus ....
Our advice is to use the new version of the mod, and we will also check the new version of the mod again in Kaspersky Anti-Virus

**Comment by 8MiYile** [comment]
[Anti-virus software test report](https://opentip.kaspersky.com/6925BC7971A96B1677D6BA61E564AE115EBAC1220F691EE076105591D7B20849/results?tab=upload)
I uploaded the latest version for the Fabric loader and the result of the test is `Clean`

**Comment by 8MiYile** [comment]
@xfl03 可以关闭issue并标记成solved了

**Comment by xfl03** [comment]
CustomSkinLoader is fully open source and build by public CI. In addition, it contains neither third party file nor native file. I do believe CustomSkinLoader doesn't includes any dangerous file.
