### ISSUE TITLE
How do I display it properly?

### ISSUE THREAD

**Issue by QueenUlyana** [JLChnToZ/MCCustomSkinLoader#257]
### Describe the bug

I don't get elitra from the texture pack. Instead, they are black. Also the cape, black. Although I'm not wearing a cape at all, I don't have a cape, but I see a black cape.

### Steps to reproduce

```bash
0
```

### Mod Version

CustomSkinLoader_Fabric-14.16.jar

### Minecraft Version

1.19.4

### Mod Loader

Fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

- [X] This problem is triggered in the latest version of the mod (if not the latest please upgrade the mod first)

**Comment by QueenUlyana** [comment]
![2023-06-10_09 42 09](https://github.com/xfl03/MCCustomSkinLoader/assets/83131824/ad0fe7b1-98c5-4d1d-a770-d083b457b7df)
![2023-06-10_09 42 20](https://github.com/xfl03/MCCustomSkinLoader/assets/83131824/a479da22-1a99-4b46-938f-12a57519a9a4)
![2023-06-10_09 43 38](https://github.com/xfl03/MCCustomSkinLoader/assets/83131824/814c8a09-44f4-4bc7-a694-e6754327b040)

**Comment by 8MiYile** [comment]
Can you post your download URL for this resource pack?
Since you're doing this now, with no errors reported and no logs, just screenshots and the environment used, we're not sure what went wrong

Here's a message for you.
```
Troubleshooting any problem without the error log is like driving with your eyes closed.
                                     —— Apache Official Document Getting Started
```

**Comment by xfl03** [comment]
More detail is needed.

**Comment by QueenUlyana** [comment]
> Can you post your download URL for this resource pack? Since you're doing this now, with no errors reported and no logs, just screenshots and the environment used, we're not sure what went wrong
> 
> Here's a message for you.
> 
> ```
> Troubleshooting any problem without the error log is like driving with your eyes closed.
>                                      —— Apache Official Document Getting Started
> ```

This skin is from the nickname "Naruto".
