### ISSUE TITLE
[Bug] 最新版MOD导致服务器端无法开启

### ISSUE THREAD

**Issue by createduser** [JLChnToZ/MCCustomSkinLoader#262]
### 描述问题

我在CurseForge中下载了最新的14.17兼容1.16.5至1.8的版本，并把它放置到了Mohist1.12.2#320端。发现这个版本的MOD在1.12.2客户端可正常游玩游戏且LitteSkin皮肤加载正常，但在Mohist中无法启动，重新下载MOD和服务端依赖库后还是无法运行。随后更换为了CatSever，依然存在这个问题下。在MC百科下载14.15版本后再次运行，这个MOD随即运行正常。由于Mohist端被我删除，只能提供CatServer及客户端的日志

### 复现步骤

```bash
1. 将于CurseForge下载的MOD文件及其其他MOD放入CatSever端的mods文件夹
2. 将于CurseForge下载的MOD文件及其其他MOD放入客户端的mods文件夹
3. 启动CatSever及客户端，CatSever随后发生崩溃，客户端可正常游玩游戏且LitteSkin皮肤加载正常
```

### 崩溃报告查看地址

客户端无崩溃，CatServer发生崩溃且无crash-reports报告

### CustomSkinLoader.log 查看地址

https://mclo.gs/88ggMwO

### latest.log 查看地址

https://mclo.gs/RArpoQP

### [仅Forge用户] Forge Log 查看地址

https://mclo.gs/9DCgfaQ

### 模组版本

14.17

### Minecraft游戏版本

1.12.2

### Minecraft启动器 名称 及 版本

Mohist1.12.2#320和Catserver（不清楚版本号，forge版本：14.23.5.2860），HMCL3.5.5

### 模组加载器

Forge

### 操作系统

Windows

### 在提交错误报告之前,有没有做到...

- [X] 先尝试搜索issues里面, 查看并确认打开或关闭的工单, 是否搜索不到

- [X] 确认你的模组版本是最新的开发版本,且文件下载正确,没有出现类似forge下载了fabric版的这类基础问题

- [X] 这个问题是在最新的mod版本触发(若不是最新的请先升级mod)

**Comment by createduser** [comment]
这里是MOD列表
![mods 2023_7_29 18_08_03](https://github.com/xfl03/MCCustomSkinLoader/assets/132128201/6a78c77f-0b59-4cd9-9815-3bcd9e3e40ef)
![mods 2023_7_29 18_07_09](https://github.com/xfl03/MCCustomSkinLoader/assets/132128201/e814fbd5-4cac-4d4f-8195-a2b30290bcfb)

**Comment by createduser** [comment]
客户端还安装了LiteLoader加载器，但没有安装任何LiteLoader的MOD

**Comment by createduser** [comment]
以下是MOD列表
![mods 2023_7_29 18_07_09](https://github.com/xfl03/MCCustomSkinLoader/assets/132128201/23621540-011a-4b58-8f58-d9b6a92a93b3)
![mods 2023_7_29 18_08_03](https://github.com/xfl03/MCCustomSkinLoader/assets/132128201/621f3b56-291f-4083-a2de-482b11615a74)

**Comment by ZekerZhayard** [comment]
CustomSkinLoader 是纯客户端 Mod，不需要装进服务端
