### ISSUE TITLE
[Bug] 进入世界一段时间后游戏报错并崩溃

### ISSUE THREAD

**Issue by IzumiiKonata** [JLChnToZ/MCCustomSkinLoader#264]
### 描述问题

在加载完世界一段时间后游戏会爆栈并抛出一个StackOverflowError

### 复现步骤

```bash
1. 进入一个世界
2. 站住不动大约一分钟
3. 游戏崩溃
```

### 崩溃报告查看地址

https://mclo.gs/tuYekeR

### CustomSkinLoader.log 查看地址

https://mclo.gs/r1s8oIo

### latest.log 查看地址

https://mclo.gs/TUtVXc5

### 模组版本

14.17 SNAPSHOT-58

### Minecraft游戏版本

1.20.1

### Minecraft启动器 名称 及 版本

我正在开发一个mod 从idea启动的

### 模组加载器

Fabric

### 操作系统

Windows

### 在提交错误报告之前,有没有做到...

- [X] 先尝试搜索issues里面, 查看并确认打开或关闭的工单, 是否搜索不到

- [X] 确认你的模组版本是最新的开发版本,且文件下载正确,没有出现类似forge下载了fabric版的这类基础问题

- [X] 这个问题是在最新的mod版本触发(若不是最新的请先升级mod)

**Comment by ImX1anyu** [comment]
我使用反编译器查看IFakeIResourceManager.class中有两个相同参数相同名字的函数 我认为这是一个编译问题

**Comment by IzumiiKonata** [comment]
*不清楚该问题是由哪个mod导致的 单独安装CustomSkinLoader不会复现

**Comment by IzumiiKonata** [comment]
nvm 有可能是开发环境抽风了
