### ISSUE TITLE
[Bug] UPDATE YOUR MOD 一直在

### ISSUE THREAD

**Issue by Mtviloldshi** [JLChnToZ/MCCustomSkinLoader#270]
### Describe the bug

已经更新到最新的MOD版本 14.18 fabric版本

### Steps to reproduce

```bash
已经更新到最新的MOD版本 14.18 fabric版本
```

### Mod Version

14.18

### Minecraft Version

1.19.4

### Mod Loader

Fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

- [X] This problem is triggered in the latest version of the mod (if not the latest please upgrade the mod first)

**Comment by xfl03** [comment]
Where is your log?
你的日志呢？

**Comment by xfl03** [comment]
新的测试版修了

**Comment by 8MiYile** [comment]
@xfl03 我的锅我的锅，忘记给CustomSkinLoader.log添加必填这个参数了
