### ISSUE TITLE
Unexpected crash on player approach

### ISSUE THREAD

**Issue by FoxJune** [JLChnToZ/MCCustomSkinLoader#271]
The client crashes when I approach someone with a custom player model (CPM mod) while using your skin feature mod.

<details>
  <summary>Crash Log</summary>
---- Minecraft Crash Report ----
// Why did you do that?
 
Time: 2023-07-03 22:26:28
Description: Unexpected error
 
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'void com.mojang.authlib.minecraft.MinecraftProfileTexture.<init>(java.lang.String, java.util.Map)'
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at com.tom.cpm.shared.definition.ModelDefinitionLoader.loadPlayer(ModelDefinitionLoader.java:137)
	at com.tom.cpm.shared.MinecraftClientAccess.getCurrentClientPlayer(MinecraftClientAccess.java:39)
	at com.tom.cpm.shared.animation.AnimationEngine.tick(AnimationEngine.java:37)
	at com.tom.cpm.client.CustomPlayerModelsClient.lambda$onInitializeClient$0(CustomPlayerModelsClient.java:34)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:47)
	at net.minecraft.class_310.handler$bcl000$fabric-lifecycle-events-v1$onStartTick(class_310.java:6511)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(Unknown Source)
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void com.mojang.authlib.minecraft.MinecraftProfileTexture.<init>(java.lang.String, java.util.Map)'
	at customskinloader.fake.FakeMinecraftProfileTexture.<init>(FakeMinecraftProfileTexture.java:15)
	at customskinloader.profile.ModelManager0.getProfileTexture(ModelManager0.java:128)
	at customskinloader.profile.ModelManager0.fromUserProfile(ModelManager0.java:110)
	at customskinloader.CustomSkinLoader.loadProfileFromCache(CustomSkinLoader.java:207)
	at customskinloader.fake.FakeSkinManager.loadSkinFromCache(FakeSkinManager.java:110)
	at net.minecraft.class_1071.handler$zik000$customskinloader$inject_loadSkinFromCache(class_1071.java:1661)
	at net.minecraft.class_1071.method_4654(class_1071.java)
	at com.tom.cpm.client.PlayerProfile$1.load0(PlayerProfile.java:187)
	at com.tom.cpm.shared.skin.PlayerTextureLoader.load(PlayerTextureLoader.java:61)
	at com.tom.cpm.shared.config.Player.getTextures(Player.java:41)
	at com.tom.cpm.shared.definition.ModelDefinitionLoader.loadPlayer(ModelDefinitionLoader.java:80)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 19 more
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at com.tom.cpm.shared.definition.ModelDefinitionLoader.loadPlayer(ModelDefinitionLoader.java:137)
	at com.tom.cpm.shared.MinecraftClientAccess.getCurrentClientPlayer(MinecraftClientAccess.java:39)
	at com.tom.cpm.shared.animation.AnimationEngine.tick(AnimationEngine.java:37)
	at com.tom.cpm.client.CustomPlayerModelsClient.lambda$onInitializeClient$0(CustomPlayerModelsClient.java:34)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:47)
	at net.minecraft.class_310.handler$bcl000$fabric-lifecycle-events-v1$onStartTick(class_310.java:6511)
 
-- Affected level --
Details:
	All players: 1 total; [class_746['VOIDDER'/584, l='ClientLevel', x=0.50, y=60.00, z=0.50]]
	Chunk stats: 4096, 38
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,60,0), Section: (at 0,12,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 102339 game time, 507942339 day time
	Server brand: Waterfall <- Purpur
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(Unknown Source)
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(Unknown Source)
 
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, replaymod_lang
 
-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 241282832 bytes (230 MiB) / 838860800 bytes (800 MiB) up to 8556380160 bytes (8160 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 2.49
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: AMD Radeon R9 200 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x6810
	Graphics card #0 versionInfo: DriverVersion=27.20.20913.2000
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 43767.03
	Virtual memory used (MB): 28810.65
	Swap memory total (MB): 11158.23
	Swap memory used (MB): 446.05
	JVM Flags: 6 total; -XX:+DisableAttachMechanism -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.4-fabric0.76.0-1.3.1
		advancementplaques: Advancement Plaques 1.4.9
		ambientsounds: Ambient Sounds (Fabric) 5.2.19
		arikeys: AriKeys 2.2
		betterthirdperson: Better Third Person 1.9.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.60
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.60
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.60
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.60
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.60
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.60
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.60
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.60
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.60
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.60
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.60
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.60
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.60
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.60
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.60
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.60
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.60
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.60
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.60
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.60
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.60
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		cpm: Customizable Player Models 0.6.8a
		creativecore: CreativeCore (Fabric) 2.10.12
			net_minecraftforge_eventbus: eventbus 6.0.4
		customskinloader: CustomSkinLoader 14.15.2
		dashloader: DashLoader 5.0.0-alpha.13+1.19.4
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
			dev_quantumfusion_taski: Taski 2.1.0
		dcch: DCCH 2.0+1.17
		debugify: Debugify 1.19.4+2.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		emotecraft: Emotecraft 2.2.7-b.build.48
			bendy-lib: Bendy api 4.0.0
			player-animator: Player Animator 1.0.2+1.19.4
		entity-view-distance: Entity View Distance 1.1.1+1.19.4
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			spruceui: SpruceUI 4.2.0+1.19.4
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.78.0+1.19.4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.26+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.5+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.43+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.53+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.8+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.7+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.4+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.26+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.30+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.38+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.40+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.2+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.7+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.3+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.19+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.0+d51205dbf4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.19+local
		faster_entity_animations: FastAnim 1.6
		ferritecore: FerriteCore 5.2.0
		firstperson: FirstpersonModel 2.2.3
		forgeconfigapiport: Forge Config API Port 6.0.2
		horsestatsvanilla: Horse Stats Vanilla 4.2.3
			libgui: LibGui 7.0.0-beta.2+1.19.4
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
		iceberg: Iceberg 1.1.10
		immediatelyfast: ImmediatelyFast 1.1.13
			net_lenni0451_reflect: Reflect 1.1.0
		invmove: InvMove 0.8.3
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.0+1.19.4
			pride: Pride Lib 1.2.0+1.19.4
		languagereload: Language Reload 1.5.7+1.19.4
		lithium: Lithium 0.11.1
		memoryleakfix: Memory Leak Fix 1.0.0
		minecraft: Minecraft 1.19.4
		modelfix: Model Gap Fix 1.10
		modmenu: Mod Menu 6.2.3
		morechathistory: MoreChatHistory 1.1.1
		moreculling: More Culling 1.19.4-0.17.0
			conditional-mixin: conditional mixin 0.3.2
		mousetweaks: Mouse Tweaks 2.24
		nochatreports: No Chat Reports 1.19.4-v2.1.6
			fabric-api-base: Fabric API Base 0.4.26+1e9487d2f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.3+504944c8f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.3+504944c8f4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.4+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.47+3bd4ab0ff4
		notenoughanimations: NotEnoughAnimations 1.6.3
		noxesium: Noxesium 0.1.8
		pehkui: Pehkui 3.7.3+1.14.4-1.20
			kanos_config: Kanos Config 0.4.0+1.14.4-1.19.4
		pekhuisyn: PekhuiSyn 1.18.2
		phosphor: Phosphor 0.8.1
		presencefootsteps: Presence Footsteps 1.8.0
			kirin: Kirin UI 1.14.0
		replaymod: Replay Mod 1.19.4-2.6.13
		rrls: Remove Reloading Screen 1.19.4-2.0.2-fabric
		smoothboot: Smooth Boot 1.19.4-1.7.0
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.19.4-1.1.1
		stendhal: Stendhal 1.3.7-1.19.4
		tooltipfix: ToolTip Fix 1.1.1-1.19.3
		vmp: Very Many Players 0.2.0+beta.7.73
		wildfire_gender: Wildfire's Female Gender Mod 1.19.3-3.0.1
		worldedit: WorldEdit 7.2.14+6360-094b734
		xaerominimapfair: Xaero's Minimap 23.4.0
		xaeroworldmap: Xaero's World Map 1.30.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.1+1.19.4
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
			yet_another_config_lib: YetAnotherConfigLib 2.5.1+1.19.4
		zoomify: Zoomify 2.9.4
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.6
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: AMD Radeon R9 200 Series GL version 3.2.14830 Core Profile Forward-Compatible Context 22.6.1 27.20.20913.2000, ATI Technologies Inc.
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: ru_ru
	CPU: 24x Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
</details>

What might be the cause of this crash?

**Comment by FoxJune** [comment]
Please add help wanted tag.

**Comment by xfl03** [comment]
Use latest mod.
