### ISSUE TITLE
[Bug] Crash in launching

### ISSUE THREAD

**Issue by 1936268516** [JLChnToZ/MCCustomSkinLoader#274]
### Describe the bug

[minecraft-exported-logs-2023-10-16T12-06-13.log](https://github.com/xfl03/MCCustomSkinLoader/files/12912038/minecraft-exported-logs-2023-10-16T12-06-13.log)

### Steps to reproduce

```bash
Error on startup. Tried again.
```

### Link to crash-report if applicable

no

### Link to CustomSkinLoader.log if applicable

no

### Link to latest.log if applicable

no

### [Only Forge User] Link to Forge Log  if applicable

no

### Mod Version

14.18.1

### Minecraft Version

1.16.5

### Minecraft Launcher Name and Version

HMCL v3.5.5

### Mod Loader

Forge

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

- [X] This problem is triggered in the latest version of the mod (if not the latest please upgrade the mod first)

**Comment by ZekerZhayard** [comment]
你的日志没上传成功

**Comment by 1936268516** [comment]
> 你的日志没上传成功

[minecraft-exported-logs-2023-10-16T13-39-25.log](https://github.com/xfl03/MCCustomSkinLoader/files/12912482/minecraft-exported-logs-2023-10-16T13-39-25.log)

**Comment by xfl03** [comment]
- Java: 1.8
- Minecraft: 1.16.5
- Forge: 36.2.39
- java.lang.ClassNotFoundException: net.minecraft.client.resources.IResourceManager

**Comment by xfl03** [comment]
#272 #273
