### ISSUE TITLE
does this work for cracked minecraft?

### ISSUE THREAD

**Issue by ISE9218** [JLChnToZ/MCCustomSkinLoader#275]
### Describe the feature

I'm using pollymc and was wondering if this skin can be used to change my skin and show it to other players.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 8MiYile** [comment]
What? It's a mod. It's a mod, it just works in fabric/forge, it's not a launcher.
