### ISSUE TITLE
[Bug] Immediate Crash after joining a server that teleports you to a second lobby

### ISSUE THREAD

**Issue by vickimsan** [JLChnToZ/MCCustomSkinLoader#278]
### Describe the bug

To prevent crashes, I've found that using CustomSkinLoader version 14.17 works best. I'm not sure what went wrong with the newer version or what's causing the crashes. I've disabled all my mods and attempted to use the latest version of CustomSkinLoader on its own, but it still crashes.

### Steps to reproduce

```bash
1. Open Feather Client and visit play.jartexnetwork.com with CustomSkinLoader mod and Optifine
2. If you don't have an account, make one. Then enter Bedwars and log out (only if you're new to the server)
3. Rejoin the server and you'll be instantly teleported to Bedwars and then you would crash afterwards
```

### Link to crash-report if applicable

https://mclo.gs/WlhqjOp

### Link to CustomSkinLoader.log if applicable

https://mclo.gs/8kPEF6c

### Link to latest.log if applicable

https://mclo.gs/zQa8r1D

### [Only Forge User] Link to Forge Log  if applicable

https://mclo.gs/4X7ch01

### Mod Version

14.18.1

### Minecraft Version

1.8.9

### Minecraft Launcher Name and Version

Feather Client

### Mod Loader

Forge

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This problem is triggered in the latest version of the mod (if not the latest please upgrade the mod first)

**Comment by ZekerZhayard** [comment]
update CustomSkinLoader to 14.18.2
