### ISSUE TITLE
关于“Update your mod”披风的一些问题

### ISSUE THREAD

**Issue by Wudji** [JLChnToZ/MCCustomSkinLoader#283]
### 描述一下

开发者们好：
关于Custom Skin Loader的“update your mod”更新提醒披风，有这样几个问题和建议：
- 有没有可以停用更新检查或者此披风的配置选项（部分发布的整合包可能无法及时更新此模组，我在网络上并没有搜索到有关此披风的关闭方法，可能是我漏掉了），如果没有此配置项的话能否添加一个此功能的配置项。
- 如果因故无法添加禁用更新检查的配置项的话，可否将更新披风提醒改得更明确一些，例如“update CSL mod”。（“update your mod”并不能有效地提醒玩家更新Custom Skin Loader模组）

### 在提交反馈或建议之前,请先确认...

- [X] 你要提交的反馈或者建议不存在于本模组的最新开发版下. 
- [X] 以及在issues或者Wiki内搜索过, 并且无结果

**Comment by xfl03** [comment]
CSL不带任何更新检测功能，出现这样的披风是第三方皮肤站/披风站导致的。
如果出现了这样的现象，请带上日志反馈问题，我们来定位是谁导致的。

**Comment by Wudji** [comment]
![2023-12-18_22 01 00](https://github.com/xfl03/MCCustomSkinLoader/assets/93850120/f8fd264e-cbea-4aaf-99d9-0017e397214e)
测试环境：
CustomSkinLoader_Fabric-15.0-SNAPSHOT-9
fabric-api-0.91.0+1.20.1
fabric loader 0.15.2

日志文件：
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/13704696/CustomSkinLoader.log)
[latest.log](https://github.com/xfl03/MCCustomSkinLoader/files/13704701/latest.log)

搜索“update your mod”词条不难看出该问题已在玩家群体中广泛出现，so。。。
（（看了一手日志貌似是 https://minecraftcapes.net/ 这个皮肤站导致的
（（好像和这个有点关系 https://github.com/xfl03/MCCustomSkinLoader/commit/00c931d434ff6aa09f04176679953031c62831c7 ，看来现在确实是修复掉了

**Comment by xfl03** [comment]
早修复好了，请用最新版Mod
