### ISSUE TITLE
与 MoreplayerModels的兼容问题

### ISSUE THREAD

**Issue by ghost** [JLChnToZ/MCCustomSkinLoader#29]
mc 版本1.12.2  
forege 14.23.1.2583
如果同时安装了  本mod（加载本地皮肤）与MoreplayerModels（默认不改变玩家模型，即还是人形）https://minecraft.curseforge.com/projects/more-player-models?gameCategorySlug=mc-mods&projectID=221939 ，则第二次进入游戏后，自定义皮肤会被MoreplayerModels自带的皮肤覆盖

**Comment by xfl03** [comment]
MPM自带了一个皮肤材质加载系统用于加载所有的人物皮肤(包括自定义模型与原始模型)

~~还请您讲诉下在您理想中这套加载系统与流程应当如何运作，我可以进行修改~~

具体MPM如何加载材质与如何处理原有材质可以参考
noppes.mpm.client.RenderEvent.loadPlayerResource(EntityPlayer pl, ModelData data)
简而言之是先让CSL进行了材质加载，然后再重新使用原有的URL进行自己的一套加载，而本地皮肤是没有可以被MPM认可的URL的，因此MPM无法加载CSL的本地材质

我可以针对这一Mod进行本地皮肤支持的ASM修改，不过不知道会不会影响到这一Mod的其他的行为

**Comment by xfl03** [comment]
以及说一句实在话，这个BUG的修复比起CSL更适合MPM去做
CSL能去做的也只是发布一个小补丁魔改MPM的相关代码
而NPM理应更加重视来自于Entity原本就有的材质

**Comment by ghost** [comment]
hmm~我也只是阐述下现象，能不能加优先级选项，CSL最后覆盖所有皮肤加载，默认不开启，然后有特殊要求的开启（比如我这种。。。）
不过不知道不动MPM代码能不能做到,要不我去找MPM报个issue？

**Comment by xfl03** [comment]
请提供下您的Minecraft版本
我制作个补丁（新的jar文件，放进mods文件夹使用）用于修复这个吧
改一下其他Mod其实挺方便的，只是不适宜在CSL中完成罢了

**Comment by ghost** [comment]
minecraft version  1.12.2
Forege 14.23.1.2583  
（1L已经说啦呀）

**Comment by HeartyYF** [comment]
33：凭啥这锅要我背，我不想背
然后非常好心的做了个fix

**Comment by ghost** [comment]
so？

**Comment by xfl03** [comment]
不是特别重要的问题，不急着修复，抱歉
~咕咕咕~

**Comment by ghost** [comment]
我也是偶尔登上来看到个  help wanted  标签，以为要进一步的信息呢~~

**Comment by xfl03** [comment]
我还是不太懂为什么这个mod硬要在皮肤加载后，重新拿着URL再去加载一次皮肤..

**Comment by NekoCaffeine** [comment]
顺便给这几个方法挂个钩子就没那么多问题了
 https://github.com/NekoCaffeine/Alchemy/blob/master/dlcs/SkinCore/src/main/java/index/alchemy/dlcs/skin/core/SkinCapability.java#L135

**Comment by ghost** [comment]
神嘛！！！！不修复了！！！强烈谴责，验证抗议，我们敦促美方（……×＆……＆×（＆）（
