### ISSUE TITLE
version for 1.20.6

### ISSUE THREAD

**Issue by ajsi123** [JLChnToZ/MCCustomSkinLoader#293]
### Describe the feature

can yall add a 1.20.6 version this should be easy right

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by SturdyFool10** [comment]
"it should be easy, right?" is a cursed phrase, sir
