### ISSUE TITLE
[Bug] CSL在24w21b中崩溃

### ISSUE THREAD

**Issue by Alterale-mcfunction** [JLChnToZ/MCCustomSkinLoader#295]
### 描述问题

CSL在1.21快照版本24w21b中不可用，使用模组加入服务器或是进入一个世界会导致客户端崩溃
在上一个快照24w20a中仍然可用

### 复现步骤

```bash
1. 加入一个服务器或者一个单人世界存档
2. 游戏崩溃
```

### 崩溃报告查看地址

https://mclo.gs/zbBoVhP

### CustomSkinLoader.log 查看地址

https://mclo.gs/FfDcpku

### latest.log 查看地址

https://mclo.gs/aUUw7JD

### 模组版本

CustomSkinLoader_Fabric-14.19.1

### Minecraft游戏版本

24w21b

### Minecraft启动器 名称 及 版本

PCL

### 模组加载器

Fabric

### 操作系统

Windows

### 在提交错误报告之前,有没有做到...

- [X] 先尝试搜索issues里面, 查看并确认打开或关闭的工单, 是否搜索不到

- [x] 确认你的模组版本是最新的开发版本,且文件下载正确,没有出现类似forge下载了fabric版的这类基础问题

- [X] 这个问题是在最新的mod版本触发(若不是最新的请先升级mod)

**Comment by paulzzh** [comment]
从24w21a开始，`net/minecraft/util/Identifier`的Constructor变成private了，因此不能用`new ResourceLocation(java.lang.String)`
https://github.com/xfl03/MCCustomSkinLoader/blob/cd1922844c735bad55f488a2059ccd0b05c9c806/Common/src/main/java/customskinloader/fake/FakeCapeBuffer.java#L15
[24w20a](https://maven.fabricmc.net/docs/yarn-24w20a+build.5/net/minecraft/util/Identifier.html#%3Cinit%3E(java.lang.String)) [24w21a](https://maven.fabricmc.net/docs/yarn-24w21a+build.1/net/minecraft/util/Identifier.html#%3Cinit%3E(java.lang.String%5B%5D)) [1.21](https://maven.fabricmc.net/docs/yarn-1.21+build.1/net/minecraft/util/Identifier.html#%3Cinit%3E(java.lang.String,java.lang.String))

可以改用[Identifier.tryParse(String id)](https://maven.fabricmc.net/docs/yarn-24w21a+build.1/net/minecraft/util/Identifier.html#tryParse(java.lang.String))(Lnet/minecraft/class_2960;method_12829(Ljava/lang/String;)Lnet/minecraft/class_2960;)，大概能解决24w21a开始到1.21存在的这个崩溃问题
但是我不太会修。。本人水平低看不太懂这个项目

**Comment by paulzzh** [comment]
通过一些Bytecode编辑确定只需把
`private static final ResourceLocation TEXTURE_ELYTRA = new ResourceLocation("textures/entity/elytra.png");`
改成
`private static final ResourceLocation TEXTURE_ELYTRA = ResourceLocation.tryParse("textures/entity/elytra.png");`
就能解决1.21上的NoSuchMethodError崩溃问题并正常工作
在有人来修之前，可以尝试自行用[Recaf](https://www.coley.software/Recaf-documentation/)编辑\<clinit\>解决
![image](https://github.com/xfl03/MCCustomSkinLoader/assets/28055560/7d976b6d-96b3-4486-b562-7522d5cab497)
因为LICENSE限制我无法分发修改后的文件

**Comment by Deniz1433** [comment]
> 通过一些Bytecode编辑确定只需把 `private static final ResourceLocation TEXTURE_ELYTRA = new ResourceLocation("textures/entity/elytra.png");` 改成 `private static final ResourceLocation TEXTURE_ELYTRA = ResourceLocation.tryParse("textures/entity/elytra.png");` 就能解决1.21上的NoSuchMethodError崩溃问题并正常工作 在有人来修之前，可以尝试自行用[Recaf](https://www.coley.software/Recaf-documentation/)编辑<clinit>解决 ![image](https://private-user-images.githubusercontent.com/28055560/340028021-7d976b6d-96b3-4486-b562-7522d5cab497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0OTUzNDIsIm5iZiI6MTcxODQ5NTA0MiwicGF0aCI6Ii8yODA1NTU2MC8zNDAwMjgwMjEtN2Q5NzZiNmQtOTZiMy00NDg2LWI1NjItNzUyMmQ1Y2FiNDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDIzNDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYzgxZTRjN2NmOWFkODU4MmRhNjdlMTZiODVmYmY0ZmVkMTQ0MmYxMzdmZDk1OTQyM2MxMGQxYTljMjg4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WFFZo-vtcgv694-WqQXG0GckwRWyzdxjJhN5RPsD-PY) 因为LICENSE限制我无法分发修改后的文件

Thanks, this works. However, since we modify the bytecode of the class, I had to re-sign the jar file, or else I'd get a SHA-256 Digest Error

谢谢，这可行。但是，由于我们修改了类的字节码，我必须重新签名 jar 文件，否则我会收到 SHA-256 摘要错误

**Comment by yuji521** [comment]
Hello Can you teach me hand to hand.

**Comment by yuji521** [comment]
能不能手把手教我啊
