### ISSUE TITLE
有没有考虑过支持 json api 呢？

### ISSUE THREAD

**Issue by printempw** [JLChnToZ/MCCustomSkinLoader#3]
像 UniSkinAPI 那样的，我觉得很不错。最近我在写一个皮肤站，很高兴看到有一个能支持加载 1.8 双层皮肤的 mod :D

**Comment by xfl03** [comment]
啊哈...可以支持的，如果有必要的话我可以做一个api规范什么的。。。以及皮肤站的话，可以先实现下传统皮肤加载地址，我一定会加入皮肤补丁的皮肤默认加载列表的

**Comment by printempw** [comment]
传统的当然是已经实现啦，只是觉得用json的话，配置文件就不需要两个了嘛

**Comment by xfl03** [comment]
能否定义一个您能接受的api？ 如果可以的话，我近几日就可加入这个功能。

**Comment by printempw** [comment]
像[这样](https://github.com/RecursiveG/UniSkinServer/blob/master/doc/UniSkinAPI_zh-CN.md)的，您觉得怎么样呢？不介意用别人的规范的话

**Comment by xfl03** [comment]
我考虑过直接使用uniskinapi，不过您不觉得，有点臃肿吗？

**Comment by printempw** [comment]
唔，你说的确实也有道理，不过mod里只需要解析json取hash，然后http request就可以了吧（判断slim模型也更方便）。

**Comment by xfl03** [comment]
目前CSL已经解决了1.7.10无法加载的问题，也即将推出1.8.8，个人认为推出一个新api以及在列表中增加新的皮肤站是有意义的。 
`{"skin":"xx","model":"xx","cape":"xx"}`看上去也比uni清爽那么一点点
以及。。能否看一眼邮箱呢

**Comment by printempw** [comment]
你发的邮件我已经回了呀？
哦哦，新 API 确实不错！
