### ISSUE TITLE
incompatibility with SkinsRestorer plugin

### ISSUE THREAD

**Issue by pavelbat3** [JLChnToZ/MCCustomSkinLoader#301]
### Describe the feature

this plugin, adds the ability to change the skin directly on the server, but with this mod skin remains the same as it was, in the CustomSkinLoader log when changing the skin through the plugin, it says that he is looking for a skin on my usual nickname, although I entered in the plugin another, you need to make CustomSkinLoader to get the skin on the nickname, which gives the plugin SkinsRestorer

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by xfl03** [comment]
Related #237

**Comment by ZekerZhayard** [comment]
Parsing the skin texture information sent from the server is a MojangAPI task, so if you want to parse the skins set by the SkinRestorer plugin, you should elevate MojangAPI to the first place in the configuration file.

**Comment by pavelbat3** [comment]
> Parsing the skin texture information sent from the server is a MojangAPI task, so if you want to parse the skins set by the SkinRestorer plugin, you should elevate MojangAPI to the first place in the configuration file.

Why i cant use tlaucher skin system or my own?
