### ISSUE TITLE
和slimefun 头颅冲突

### ISSUE THREAD

**Issue by zwtdj** [JLChnToZ/MCCustomSkinLoader#31]
弱弱的问下，能否解决和slimefun里面的skull 的显示问题，或者和slimefun的作者勾通下？

**Comment by HeartyYF** [comment]
https://github.com/xfl03/MCCustomSkinLoader/issues/30
解决了，自己关issue吧。
以后发issue之前自己看一遍closed的。

**Comment by HeartyYF** [comment]
好好看一遍#30去

**Comment by zwtdj** [comment]
上面说禁用CSL，这个怎么禁用？下载的文件比#30早。后来发的网盘下载也失效的。

**Comment by xfl03** [comment]
与 #30 重复，请参考先前的issue
修复bug的commit为https://github.com/xfl03/MCCustomSkinLoader/commit/b50e6a934f221685512120ec724aed9ea40cb404
 在此之后的revision均已修复这个bug，未正式发布，不过您可以自行编译
编译方法就是 `gradle clean build` 已经非常方便了
