### ISSUE TITLE
[Bug] 最新版本在NeoForge中不起作用，被认为是Forge模组

### ISSUE THREAD

**Issue by lzm11111111** [JLChnToZ/MCCustomSkinLoader#313]
### Describe the bug

当在NeoForge中安装最新版的万用皮肤补丁时，会被认为是Forge模组，导致无法加载

![2024-11-07_17 42 08](https://github.com/user-attachments/assets/6858c51f-47d0-4170-a40f-d8a60a9f7db5)

### Steps to reproduce

```bash
1. 
2. 
3.
```

### Link to CustomSkinLoader.log if applicable

Nope

### Mod Version

Forge V2 14.21

### Minecraft Version

1.21.1

### Minecraft Launcher Name and Version

PCL

### Mod Loader

Forge

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

- [X] This problem is triggered in the latest version of the mod (if not the latest please upgrade the mod first)

**Comment by ZekerZhayard** [comment]
你应该装标着 ForgeV3 的版本
