### ISSUE TITLE
[Bug] NativeImage cannot be cast to class customskinloader.fake.itf.IFakeNativeImage when legacy skin is loaded on Forge (but not on Fabric)

### ISSUE THREAD

**Issue by Fourmisain** [JLChnToZ/MCCustomSkinLoader#314]
### Describe the bug

This originated from https://github.com/dzwdz/chat_heads/issues/117

Loading a legacy skin crashes on Forge (using ForgeV2_14.21), but not on Fabric, using (Fabric_14.21).

### Steps to reproduce

```bash
1. In CustomSkinLoader.json, place `LocalSkin` first in `loadlist`
2. Put any legacy skin like https://mskins.net/en/skin/renagabe-w1RoX at LocalSkin\skins\USERNAME.png
3. Load a world and wait for the skin to load - the game crashes instead
```

### Link to crash-report if applicable

https://mclo.gs/KfhXFa5

### Link to CustomSkinLoader.log if applicable

https://mclo.gs/nxW5C6L

### Link to latest.log if applicable

https://mclo.gs/EFN1Jyx

### Mod Version

14.21

### Minecraft Version

1.20.1

### Minecraft Launcher Name and Version

PrismLauncher 9.1

### Mod Loader

Forge

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

- [X] This problem is triggered in the latest version of the mod (if not the latest please upgrade the mod first)

**Comment by ZekerZhayard** [comment]
#315
