### ISSUE TITLE
和slimefun 头颅冲突

### ISSUE THREAD

**Issue by zwtdj** [JLChnToZ/MCCustomSkinLoader#32]
我下载的CustomSkinLoader_Forge-14.7依然有问题，我的是1.12.2服务器。

![image](https://user-images.githubusercontent.com/12005261/36093592-1689d11e-1026-11e8-9912-d95d6b94e49a.png)

**Comment by HeartyYF** [comment]
我的天你不能好好看一遍#30吗，或者你不知道怎么reopen一个issue？

**Comment by xfl03** [comment]
与 #30 #31 重复，请参考先前的issue
