### ISSUE TITLE
Running with OptiFine (1.13.1)

### ISSUE THREAD

**Issue by kripesh101** [JLChnToZ/MCCustomSkinLoader#37]
### Help Wanted
I have been unable to get CSL running with OptiFine in 1.13.1.

(I am **able** to get either OptiFine or CSL working in 1.13.1)
***
I think my JSON file in the `versions` directory is incorrectly setup.
Could you please post a JSON file *(and any additional instructions)* for CSL to run **with** OptiFine?

#### Additional Information
I managed to get a custom JAR to be created by adding the OptiFine `--tweakclass` argument and the OptiFine libraries to the CSL JSON file **but** the game crashes with error - `Found multiple arguments for option version, but you asked for only one`

**Comment by HeartyYF** [comment]
[1.13.1-CSL-14.10-OF-E3.json](https://github.com/xfl03/MCCustomSkinLoader/files/2497790/1.13.1-CSL-14.10-OF-E3.txt)
You know it should be a json file, but Github doesn't permit uploading files with that extension. Change the extension yourself.

**Comment by xfl03** [comment]
Using the json file provided above is able to get CSL and OF together in 1.13.1 .
#### Additional Information
Please just choose one of CSL or OF tweakClass argument to add in json, it can work correctly.

**Comment by kripesh101** [comment]
Thank you!

**Comment by Dylan-Madigan** [comment]
Having trouble getting this to work in a forge based modpack through the tekkit launcher on 1.12.2, anything specific i need to know?
