### ISSUE TITLE
[Request] Update for 1.13.2

### ISSUE THREAD

**Issue by kripesh101** [JLChnToZ/MCCustomSkinLoader#38]
1.13.2 has been out for a while but the mod has yet not been updated to support the new version. If the mod is encountering any technical issues that is preventing an update to 1.13.2, any estimations for when the issue will be fixed?

**Comment by xfl03** [comment]
We are waiting for [MinecraftForge/MCPConfig](https://github.com/MinecraftForge/MCPConfig) .
When they update for 1.13.2, this mod will update soon.

If others can provide mcp-srg map, we will also update.

**Comment by kripesh101** [comment]
MCPConfig has been updated. Waiting for mod to update.

**Comment by xfl03** [comment]
Commit: https://github.com/xfl03/MCCustomSkinLoader/commit/7a3dc4f9c2c112a914f41b17b8c8d6a4c634e9d7
Download: [CircleCI](https://43-18766989-gh.circle-artifacts.com/0/home/circleci/repo/build/libs/CustomSkinLoader_1.13.2-14.10-SNAPSHOT-43.jar)
Updated for 1.13.2 and waiting for test.

**Comment by kripesh101** [comment]
Thank you! Works perfectly!

**Comment by n-aspen** [comment]
I'm unable to get this to load by modifying the existing json files. I've tried removing the URL from the library statement, updating with the new file name, and updating the inherit statement and it says that the library is invalid

**Comment by xfl03** [comment]
@mov51 I made a guide for 1.13.2 installation, you can have a look.
https://github.com/xfl03/MCCustomSkinLoader/wiki/1.13.2-Install-Guide
