### ISSUE TITLE
一个皮肤加载问题

### ISSUE THREAD

**Issue by SekiBetu** [JLChnToZ/MCCustomSkinLoader#39]
如果我在skinme和blessing skin都注册了同一个玩家ID，用了不同的皮肤，那默认会显示成哪一个网站的皮肤？

**Comment by HeartyYF** [comment]
https://github.com/xfl03/MCCustomSkinLoader#default-load-list

**Comment by tnqzh123** [comment]
CSL 会根据加载列表中的顺序来加载材质。

**Comment by xfl03** [comment]
会按照加载列表中的顺序来加载皮肤，默认设置下会先加载来自blessing skin的皮肤
