### ISSUE TITLE
最新稳定版的forge版本无法加载CustomSkinLoader

### ISSUE THREAD

**Issue by tytannial** [JLChnToZ/MCCustomSkinLoader#4]
使用的forge-1.7.10-10.13.4.1588-1.7.10 官方推荐的稳定版本 但是无法使用CustomSkinLoader
旧版本没有游戏开始的那个载入界面的Forge无问题

**Comment by tytannial** [comment]
测试了下1.7.10版的 forge 10.13.3.1387 以及之前的版本可以加载 CustomSkinLoader 且功能正常 
之后的版本可以加载CustomSkinLoader 但是无效果

**Comment by xfl03** [comment]
请打开对应的json(基本是.minecraft/versions/1.7.10/1.7.10.json)，找到
```
"name": "com.mojang:authlib:1.5.xx"
```
（xx可代表任意数字，很有可能等于21），将xx改为16，形如
```
    "name": "com.mojang:authlib:1.5.16"
```
保存，启动游戏。
如果仍然不能加载，请关闭游戏后再次打开这个json，
确认下这一行是不是被还原了（即16重新变成了xx），如果被还原了，请参考4.2.8来应对还原机制。
以及请确认您的启动器能否正确读取json，不能随json变更启动参数的启动器请果断放弃。  
  
复制自[[1.6.4-1.8.9][开源][二次开发]万用皮肤补丁 支持高清皮肤和所有皮肤站+兼容正版](http://www.mcbbs.net/thread-269807-1-1.html)

**Comment by tytannial** [comment]
好的 我去看看

**Comment by tytannial** [comment]
OK了 谢谢

**Comment by xfl03** [comment]
CustomSkinLoader 13.2已经修复这一bug
