### ISSUE TITLE
[Help] How to install

### ISSUE THREAD

**Issue by hitech95** [JLChnToZ/MCCustomSkinLoader#41]
Sorry, I don't understand Chinese or Mandarin (No idea how it is called).

I would like to install this mod on a MC 1.13.2 server. I tried Rift but looks like that they stopped at 1.13 and the Sponge Mixins and reflections don't work (obviously) on the newer 1.13.2.

CAn you quickly explain to me how to install?

I tried to patch the server jar but nothing happens.
I'm missing something?

**Comment by kripesh101** [comment]
This is a client-side mod.

**Comment by xfl03** [comment]
1. Chinese
2. It is a client-side mod, you need only install it in client.
3. I made a guide for 1.13.2 installation, please have a look.
https://github.com/xfl03/MCCustomSkinLoader/wiki/1.13.2-Install-Guide

**Comment by xfl03** [comment]
No further information provided.
