### ISSUE TITLE
申请默认皮肤站列表

### ISSUE THREAD

**Issue by hempflower** [JLChnToZ/MCCustomSkinLoader#44]
站点URL:https://mcskin.i-creator.cn
基于Blessing 皮肤站程序搭建

**Comment by hempflower** [comment]
要凉的节奏
![tim 20190215194037](https://user-images.githubusercontent.com/22955496/52854425-5508c800-3159-11e9-887f-2a34bed2e694.png)

**Comment by yushijinhun** [comment]
我反对，理由是你的皮肤站不支持 HTTPS。

**Comment by NekoCaffeine** [comment]
> 我反对，理由是你的皮肤站不支持 HTTPS。

我觉得也是

**Comment by hempflower** [comment]
> 我反对，理由是你的皮肤站不支持 HTTPS。

这个问题好办，马上解决。

**Comment by tnqzh123** [comment]
我也感觉你要凉
参见 #13

**Comment by hempflower** [comment]
> 我也感觉你要凉
> 参见 #13

我看到了，所以.....

**Comment by NekoCaffeine** [comment]
我觉得CSL还不如给个命令来添加皮肤站（

**Comment by tnqzh123** [comment]
@NekoCaffeine
CustomSkinLoader GUI 了解一下？

**Comment by NekoCaffeine** [comment]
那还不如整合到游戏内 也就一两个类的事情 我作为用户懒得在游戏外折腾

**Comment by hempflower** [comment]
皮肤站已支持https,同时MaHua's mirror cdn镜像也支持https!

**Comment by hempflower** [comment]
gugugu?

**Comment by tnqzh123** [comment]
33 在旅游呢
等他回来可能会处理吧
（不过估计是要凉

**Comment by hempflower** [comment]
凉了也没关系，有重写皮肤站的计划

**Comment by NekoCaffeine** [comment]
> 凉了也没关系，有重写皮肤站的计划

皮肤站那么多 还不如做游戏内换肤

**Comment by yushijinhun** [comment]
我认为皮肤站进入默认加载列表，需要获得排在它位置之后的皮肤站的同意。

**Comment by hempflower** [comment]
>我认为皮肤站进入默认加载列表，需要获得排在它位置之后的皮肤站的同意。

(黑人问号)

**Comment by tnqzh123** [comment]
@yushijinhun 那我怕是要表示强烈反对了

**Comment by xfl03** [comment]
首先感谢您使用Blessing Skin为广大的Minecraft用户提供了皮肤与登录服务！

在计划即将删去已经无法正常访问的SkinMe后，CustomSkinLoader将会从以下四个在线皮肤源按次序获取皮肤：
- [Mojang](http://www.minecraft.net/) (Mojang API)
- [LittleSkin](https://littleskin.cn/) (CustomSkinAPI)  
- [Blessing Skin](http://skin.prinzeugen.net/) (CustomSkinAPI)
- [ElyBy](http://docs.ely.by/) (ElyByAPI)

希望您可以对选入列表的规则稍作理解：
- 皮肤站知名度
例如Mojang与原先的SkinMe，均是广大用户最常使用的皮肤站，我们加入这样的皮肤站可以有效减轻修改配置文件的操作，尽力给予大部分用户开箱即用的体验
- 鼓励原创
无论用户数量多少，我们都鼓励优秀的原创皮肤站，例如Blessing Skin演示站与ElyBy均是因此加入了列表，曾经也加入过OneSkin等优秀的原创皮肤站，可惜他们停止了运营，因此通过这个列表，我们希望可以帮助推广优秀的原创皮肤站，让他们有更强的资源与动力为用户提供方便的服务

LittleSkin是皮肤补丁开发5年来一个极其特殊的例子，BS演示站在推广后不堪重负，在开发者621的授权下，我们在BS讨论群中公平公开公正的评测了所有愿意开放的皮肤站，最后LittleSkin脱颖而出加入了列表。

我们极其希望可以看到您的原创部分，愿意尽自己的努力帮助支持优秀的原创者！
