### ISSUE TITLE
How can i use forge 1.13.2 with skin loader

### ISSUE THREAD

**Issue by robertmakrytski** [JLChnToZ/MCCustomSkinLoader#45]
https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.13.2.html

**Comment by xfl03** [comment]
Forge broke coremods :(
In 1.13.2, coremods have to use JavaScript to transform Minecraft. I think it is not a good design and I must spend a lot of time to do it.
So please wait or let Forge revert the coremod system.

**Comment by xfl03** [comment]
Almost done, please have a test, thanks!
Commit: https://github.com/xfl03/MCCustomSkinLoader/commit/b2867a0dbf0d44c83391198e8789aa6001aa72b3
Download: https://csl.littleservice.cn/libraries/customskinloader/CustomSkinLoader_Forge/14.10-SNAPSHOT-65/CustomSkinLoader_Forge-14.10-SNAPSHOT-65.jar

**Comment by xfl03** [comment]
It works?

**Comment by robertmakrytski** [comment]
1)How can i config version.json from forge + custom skin loader?

**Comment by xfl03** [comment]
After installed forge, just install it like a normal mod, put the jar into .minecraft/mods folder.

**Comment by robertmakrytski** [comment]
yes. it works

**Comment by xfl03** [comment]
Released.
https://github.com/xfl03/MCCustomSkinLoader/releases/tag/14.10
