### ISSUE TITLE
Skin loads in one computer only

### ISSUE THREAD

**Issue by sonic1crack** [JLChnToZ/MCCustomSkinLoader#46]
Hello!

I use minecraft in both my laptop and my pc. I have customskinloader in both but only works for my laptop, which was the first one to be installed in. Is it possible that there's an issue doing that? I don't know how to fix it because there's no error or anything. 

Thanks in advance :)

**Comment by xfl03** [comment]
Please provide the log file `.minecraft/CustomSkinLoader/CustomSkinLoader.log` from both your laptop and pc, thanks.
