### ISSUE TITLE
1.14.1

### ISSUE THREAD

**Issue by mitchngwen** [JLChnToZ/MCCustomSkinLoader#54]
How do I install this on 1.14.1? Install instruction are for 1.14 and not for 1.14.1 I am using MultiMC.

**Comment by xfl03** [comment]
Fabric edition will be released, please wait for some hours.

**Comment by xfl03** [comment]
Thanks for @ZekerZhayard , 1.14.x Fabric support is finished.
You can download it at [CurseForge](https://minecraft.curseforge.com/projects/customskinloader).

**Comment by mitchngwen** [comment]
Thank you so much it works great! I was wondering is there any way to switch skin while in game trough a GUI or command?

**Comment by xfl03** [comment]
Not supported now.
