### ISSUE TITLE
Not work with Forge 1.13.2-25.0.205

### ISSUE THREAD

**Issue by robertmakrytski** [JLChnToZ/MCCustomSkinLoader#57]
doesn't work correct from this forge version

**Comment by xfl03** [comment]
Please provide fml client log and CustomSkinLoader log if exists.

**Comment by robertmakrytski** [comment]
this is for last version forge 219
`> [23:16:29.039] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2400ms or 48 ticks behind
> [23:16:29.856] [Client thread/INFO] [minecraft/AdvancementList]: Loaded 0 advancements
> [23:16:29.996] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:<init>:50]: Log Path: C:\Users\rob1\AppData\Roaming\.minecraft\CustomSkinLoader\CustomSkinLoader.log
> [23:16:29.999] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] CustomSkinLoader 14.10-SNAPSHOT-65
> [23:16:30.000] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] DataDir: C:\Users\rob1\AppData\Roaming\.minecraft\CustomSkinLoader
> [23:16:34.579] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
> [23:16:34.606] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World'/minecraft:overworld
> [23:16:36.710] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: rob77911 lost connection: Disconnected
> [23:16:36.711] [Server thread/INFO] [minecraft/MinecraftServer]: rob77911 left the game
> [23:16:36.737] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Stopping singleplayer server as player logged out
> [23:16:36.739] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
> [23:16:36.740] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
> [23:16:36.740] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
> [23:16:36.740] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World'/minecraft:overworld
> [23:16:37.173] [Client thread/INFO] [minecraft/Minecraft]: Stopping!
> [23:16:37.753] [Client thread/INFO] [minecraft/SoundManager]: SoundSystem shutting down...
> [23:16:38.019] [Client thread/INFO] [minecraft/SoundManager]: SoundSystem Author: Paul Lamb, www.paulscode.com`
This is for work version
`> [23:14:03.079] [Server thread/INFO] [MinecraftServer/]: Saving chunks for level 'New World'/minecraft:overworld
> [23:14:03.681] [Server thread/WARN] [MinecraftServer/]: Can't keep up! Is the server overloaded? Running 2594ms or 51 ticks behind
> [23:14:04.625] [Client thread/INFO] [AdvancementList/]: Loaded 0 advancements
> [23:14:04.816] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:<init>:50]: Log Path: C:\Users\rob1\AppData\Roaming\.minecraft\CustomSkinLoader\CustomSkinLoader.log
> [23:14:04.820] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] CustomSkinLoader 14.10-SNAPSHOT-65
> [23:14:04.821] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] DataDir: C:\Users\rob1\AppData\Roaming\.minecraft\CustomSkinLoader
> [23:14:04.828] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] Minecraft: null()
> [23:14:04.834] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] Config File: C:\Users\rob1\AppData\Roaming\.minecraft\CustomSkinLoader\CustomSkinLoader.json
> [23:14:04.836] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] Try to load config.
> [23:14:04.920] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] Successfully load config.
> [23:14:04.956] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] version : 14.10
> [23:14:04.959] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] enableDynamicSkull : true
> [23:14:04.959] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] enableTransparentSkin : true
> [23:14:04.959] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] ignoreHttpsCertificate : false
> [23:14:04.960] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] forceLoadAllTextures : false
> [23:14:04.962] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] enableCape : true
> [23:14:04.962] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] cacheExpiry : 30
> [23:14:04.962] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] enableUpdateSkull : false
> [23:14:04.962] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] enableLocalProfileCache : false
> [23:14:04.962] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] enableCacheAutoClean : false
> [23:14:04.962] [pool-6-thread-1/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [pool-6-thread-1 INFO] loadList : 6
> [23:14:04.972] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Loading rob77911's profile.
> [23:14:04.972] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] 1/6 Try to load profile from 'Mojang'.
> [23:14:04.993] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Try to load from cache 'C:\Users\rob1\AppData\Roaming\.minecraft\CustomSkinLoader\caches\6edd93252f7ad77329bf0840e1c45e5d42d248d6'.
> [23:14:04.994] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Profile not found.(rob77911's profile not found.)
> [23:14:04.994] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] 2/6 Try to load profile from 'LittleSkin'.
> [23:14:05.012] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Try to load from cache 'C:\Users\rob1\AppData\Roaming\.minecraft\CustomSkinLoader\caches\8c71952e698130045bd58796add710f01d6a379d'.
> [23:14:05.017] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Both skin and cape not found.
> [23:14:05.017] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] 3/6 Try to load profile from 'BlessingSkin'.
> [23:14:05.371] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Profile not found.
> [23:14:05.372] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] 4/6 Try to load profile from 'ElyBy'.
> [23:14:05.391] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Try to load from cache 'C:\Users\rob1\AppData\Roaming\.minecraft\CustomSkinLoader\caches\c540f7a06becacdbc171db2eb782b6876b6d512a'.
> [23:14:05.393] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Profile not found.
> [23:14:05.394] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] 5/6 Try to load profile from 'SkinMe'.
> [23:14:06.204] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Error 404: User not found.
> [23:14:06.204] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] 6/6 Try to load profile from 'LocalSkin'.
> [23:14:06.209] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] Both skin and cape not found.
> [23:14:06.211] [rob77911/INFO] [STDOUT/]: [customskinloader.Logger:log:70]: [rob77911 INFO] rob77911's profile not found in load list.
> [23:14:14.072] [Server thread/INFO] [integrated.IntegratedServer/]: Saving and pausing game...`
I think it is enough.

**Comment by robertmakrytski** [comment]
better i send the file(full)
https://dropmefiles.com/fYaiB
Co i don't understand how i can save files with github

**Comment by xfl03** [comment]
Which skin site did you use for `rob77911`? 

Result in main providers:
* Mojang API, 204 No content (https://api.mojang.com/users/profiles/minecraft/rob77911)
* LittleSkin, empty (https://littleskin.cn/rob77911.json)

BTW, I suggest to use CustomSkinLoader 14.10a.

**Comment by robertmakrytski** [comment]
you can use this ninkname - lover_mine_g1
the library doesn't send request at the server.
You have tested and found different.

**Comment by robertmakrytski** [comment]
the problem happened from version 205-219

**Comment by xfl03** [comment]
Can you make sure 204 can work correctly?

**Comment by robertmakrytski** [comment]
https://files.minecraftforge.net/
i can't download this versino
i could download only 198.

**Comment by xfl03** [comment]
Please check the latest support version, thanks.

**Comment by xfl03** [comment]
Forge 199 updated ModLauncher to 1.1, and not load class from URLClassLoader.
This bug may be fixed, please have a test.
Download: https://csl.littleservice.cn/libraries/customskinloader/CustomSkinLoader_Forge/14.11-SNAPSHOT-83/CustomSkinLoader_Forge-14.11-SNAPSHOT-83.jar

**Comment by robertmakrytski** [comment]
worked

**Comment by robertmakrytski** [comment]
i want to build 1.13.2 myself, but how can i do it?
1)i should use old commit or i can do changes with current code(last commit(but when i created i see only 1.14.2 jars)
2) example i want to build 1.13.2 from this commit and check [https://github.com/xfl03/MCCustomSkinLoader/issues/57](57)  
How should i do it?

**Comment by robertmakrytski** [comment]
solved

**Comment by xfl03** [comment]
The latest jar can be used in 1.8-1.14.2 , no need to build a special version for 1.13.2 .
