### ISSUE TITLE
1.14.2 vanilla support

### ISSUE THREAD

**Issue by tiserkoven** [JLChnToZ/MCCustomSkinLoader#58]
Hello. When is vanilla 1.14.2 support planned?

**Comment by xfl03** [comment]
Why not use Fabric?

**Comment by tiserkoven** [comment]
This is not the best idea, there should be an alternative to vanilla, I think not only me.

**Comment by xfl03** [comment]
https://github.com/xfl03/MCCustomSkinLoader/commit/7fad8c602dbf11ab956079f1bec90fb720a424e4
https://csl.littleservice.cn/libraries/customskinloader/CustomSkinLoader_1.14.2/14.11-SNAPSHOT-85/CustomSkinLoader_1.14.2-14.11-SNAPSHOT-85.jar
Please have a try.
