### ISSUE TITLE
[1.8] Citizens 插件 无法显示NPC的皮肤

### ISSUE THREAD

**Issue by xyblues** [JLChnToZ/MCCustomSkinLoader#6]
我在服务器内使用 Citizens 插件 可是装了您的MOC却无法显示NPC的皮肤了
这个问题能够解决吗？ 不装就看得见 装了就看不见了 希望能解决 谢谢了

**Comment by xfl03** [comment]
尝试考虑下NPC mod？
NPC插件并不是很了解。

**Comment by xyblues** [comment]
呐呐 纯净服OwO 装不了MOD 如果不能解决就算了

**Comment by xyblues** [comment]
也不是什么大事 谢谢了

**Comment by xfl03** [comment]
不太了解这个插件的皮肤分发原理，不知道您是否知晓？

**Comment by xfl03** [comment]
啊我发现原因了，请问您的minecraft版本是多少？我立即修复

**Comment by xyblues** [comment]
谢谢 1.8.8

**Comment by xfl03** [comment]
噗。。。。版本搞错我给满分

**Comment by xyblues** [comment]
等会你更新完之后我应该在哪里下载呢OwO 不太会用github

**Comment by xfl03** [comment]
我只是提交了代码，编译的话可能需要一点时间，如果编译完了我就会发布到mcbbs，到时候再通知您。

**Comment by xyblues** [comment]
好的谢谢

**Comment by xfl03** [comment]
好了，已发布

**Comment by xyblues** [comment]
虽然发布了 可是测试还是无效...... 13.3版本一样无法显示NPC皮肤
在这个插件的配置文件里的有关皮肤是这样的 不知道对你有没有作用
他的原理我也不懂 我懵逼一个......
`    metadata:
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE0NTgzNTkyMTk4MDEsInByb2ZpbGVJZCI6Ijg3ZTE4MTQwMGVhYjQyZmY4YmY4NWM4ZDBlYTU5MjZiIiwicHJvZmlsZU5hbWUiOiJYWUJsdWUiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2FjNDhiYmYwYTY5ZGQ3Y2Q2ZWZhMTA2NDhiMTg5MTU0ZmNkMDhmOTVhY2EwZDI5Yjk3NGFhYWJjZjlhODRmOCJ9fX0=
      cached-skin-uuid-name: xyblue
      cached-skin-uuid: 87e18140-0eab-42ff-8bf8-5c8d0ea5926b
      player-skin-name: xyblue
      player-skin-signature: iK/8Wp/sP11n62Sd+dvnrjp5fvjBMCmOhg5nsFiuVQwpuN03Hzr/Y5oWCoBNHSTH/4HJNfEY4r9GjSacWRAXKf5BGBUS7DFfvwMEfEjmS4TSEpO1JUWgywXWI/GCCZ0ZfM48DioY9OjN/Tthoomi+ATOrBizXqPj82oxkl6S2w1yD6FH0CYa05LOn93CgpMU0PuEZDBayUUWRfh0/PMI4JISGOTwrYc3vDY3clKCj3JwWK3hbwjLmkAbbt5qDyw5N/EYMh8EeZKD3GEkX2gnegRNizlWzCb7VvcozB2SWUdvhe2J22aaYNJ3NxpPLmdv65TF1VkWiT4xYSqK0vnA1YlFHG6vCRyb+6qFu7XHJY1AYV5at6/sWNXepQqvEs83bhxCGEhg9f6+uqbwA4vP1C03HFPkcnCYpI0txcDddhxA5ptuIPjwhkgrgDFrn1Ku2nVk75Wv8bs8XU9ONE21zzN6FYA5RfsYW6sM9aEpOVLMhqNnPoHqZaXbYJ5YcCSwr2tl76uTwkZfm/MLrYsBegim/jy88Y1+FBuwQENN+CrDirjNRbRf80o89s+AVJKBmIxCnh3HcpqGIJHj3pUqXyI+eN1T+x/FZIavVcCu2YleHCwPqSTOYdfeIvhC7MP28mAGiakv+PPMMkOifg+yRMzzXi5rcT+W/aXd048YJB8=
    name: "\xa79\xa7l\u52a0\u5165\u6e38\u620f"
    uuid: 6b2a3ecf-1774-4a36-9d43-268699c8c9d1`

**Comment by xfl03** [comment]
那也要给我一下CSL的log吧

**Comment by xyblues** [comment]
[CustomSkinLoader.txt](https://github.com/JLChnToZ/MCCustomSkinLoader/files/180663/CustomSkinLoader.txt)

**Comment by xfl03** [comment]
npc的名字叫什么？

**Comment by xyblues** [comment]
我查看了log 发现搜索不到NPC的名字.

**Comment by xfl03** [comment]
可以加我QQ 帮我做点测试吗？
