### ISSUE TITLE
Forge 1.14.3 Crash

### ISSUE THREAD

**Issue by ShayBox** [JLChnToZ/MCCustomSkinLoader#60]
Seems you haven't provided the `reobfJar` jar for forge 1.14
here's the crash report https://paste.nomsy.net/wijucabira

**Comment by HeartyYF** [comment]
By now csl can only be loaded with Fabric in 1.14.3.

**Comment by ZekerZhayard** [comment]
I couldn't reproduce this issue with the same forge version.

```
Memory: 1624681824 bytes (1549 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
```
It may be caused by not enough memory to load the class. (?)

**Comment by xfl03** [comment]
Reproduced by using `14.10a` in 1.14.3, which supports 1.8-1.13.2.
Please use `14.11-s89`, it can be downloaded in [CurseForge](https://www.curseforge.com/minecraft/mc-mods/customskinloader/files/2729604).
