### ISSUE TITLE
1.14.3 vanilla support

### ISSUE THREAD

**Issue by tiserkoven** [JLChnToZ/MCCustomSkinLoader#61]
Make support 1.14.3 vanilla please

**Comment by xfl03** [comment]
Why not use Fabric?（Again）

**Comment by tiserkoven** [comment]
Vanilla the best (sorry), but I'm not the one who is waiting for your mod

**Comment by xfl03** [comment]
Feel sorry about it, but I think Fabric and Forge is a better way.

**Comment by xfl03** [comment]
1.14.4 vanilla supported
Commit: https://github.com/xfl03/MCCustomSkinLoader/commit/100e661ac59f19b70d40f48bf12201ec168effc7
Download: https://csl.littleservice.cn/libraries/customskinloader/CustomSkinLoader_1.14.4/14.12-SNAPSHOT-95/CustomSkinLoader_1.14.4-14.12-SNAPSHOT-95.jar
or
https://csl.littleservice.cn/versions/1.14.4-CSL-14.12-s95/1.14.4-CSL-14.12-s95.json
