### ISSUE TITLE
WILL NOT work with 1.14.4 fabric.

### ISSUE THREAD

**Issue by salmornal** [JLChnToZ/MCCustomSkinLoader#62]
Whatever i try this will not work with fabric. I have the fabric api, fabric loader and modmenu (for fabric). Modmenu allows you to see which mods you have on your fabric client and it is accepting customskinloader as a mod but my skin won't appear. It is definitely located in the LocalSkins/skins directory.

**Comment by xfl03** [comment]
@ZekerZhayard

**Comment by ZekerZhayard** [comment]
I couldn't reproduce this issue. It works very well for me, including loading local skins.  
Could you upload your logs? (`.minecraft/CustomSkinLoader/CustomSkinLoader.log` and `.minecraft/logs/latest.log`)

**Comment by xfl03** [comment]
No more information, please reopen issue if needed,
