### ISSUE TITLE
Skin server

### ISSUE THREAD

**Issue by userbig** [JLChnToZ/MCCustomSkinLoader#63]
Howdy.

I cant find any options, commands etc. to change or bind skin server to specific user or even for whole minecraft server.
Running latest forge server and want to bind to littleskin.

**Comment by tnqzh123** [comment]
> I'm sorry for my bad English :-( 

Hi @userbig:

I'm the administrator of LittleSkin.

You needn't change any options or use any command in the game. What you should do is:
1. Register on our website(https://littleskin.cn)
2. Upload your skin and/or cape to the Skin Library
3. Create your player(using your in game name)
4. Set your skin and/or cape to your player

Visit https://littleskin.cn/manual for more information(Simplified Chinese only, sorry :-(

If you need any further help, welcome to join our Telegram group: https://t.me/littleskin

**Comment by userbig** [comment]
@tnqzh123, this works same for prinzeugen (Blessing Skin)?
As i can see LittleSkin site is really slow for me?

**Comment by xfl03** [comment]
Install CustomSkinLoader in client can works for Little Skin and Blessing Skin.
Client side only, do not install in server.
