### ISSUE TITLE
cant load hd skins/capes because no system supports it

### ISSUE THREAD

**Issue by SDUBZ** [JLChnToZ/MCCustomSkinLoader#64]
if you know a place where i can actually upload the skin to my username

**Comment by xfl03** [comment]
LittleSkin
https://littleskin.cn

**Comment by SDUBZ** [comment]
does this support 1024 skins

**Comment by tnqzh123** [comment]
@SDUBZ What's "1024 skins" means?

LittleSkin support all skins with 64px\*n wide and 32px\*n or 64px\*n height skins.

For more informations and the usage, please visit our manual(Simplified Chinese only, but you could use Google Translate): https://littleskin.cn/manual

But, LittleSkin is very lag in some regions outside Mainland China. We are working on optimizing it. You can use [Blessing Skin](https://skin.prinzeugen.net) right now, which is the same with LittleSkin but more faster than LittleSkin, but Blessing Skin might be merged to LittleSkin in the future.

> Sorry for my bad English :-(

**Comment by SDUBZ** [comment]
ok i will show you the skin and cape im trying to sue with your mod 
![SDUBZ_](https://user-images.githubusercontent.com/14084377/64072534-9155dd00-ccd3-11e9-85b4-837f52ee482d.png)

![SDUBZ_](https://user-images.githubusercontent.com/14084377/64072536-97e45480-ccd3-11e9-93d9-e43db037e117.png)

**Comment by tnqzh123** [comment]
@SDUBZ Obviously, LittleSkin(and Blessing Skin) support your textures.
![image](https://user-images.githubusercontent.com/16630630/64077369-92523300-cd02-11e9-8926-ec820e116573.png)
![image](https://user-images.githubusercontent.com/16630630/64077373-9da55e80-cd02-11e9-9abe-fa9e8af9080f.png)

**Comment by SDUBZ** [comment]
Its still not loading the skin even with me using blessing skin
found the problem 
you are calling from
{
      "name": "BlessingSkin",
      "type": "CustomSkinAPI",
      "root": "http://skin.prinzeugen.net/"
    },

and not 

{
      "name": "BlessingSkin",
      "type": "CustomSkinAPI",
      "root": "https://skin.prinzeugen.net/"
    },

@xfl03

**Comment by xfl03** [comment]
Did not it be redirected?

**Comment by SDUBZ** [comment]
doesnt even seem to load the other urls apart from mojangs

**Comment by xfl03** [comment]
@SDUBZ Certainly, it can load from 3-rd part urls.
