### ISSUE TITLE
Support for capes from minecraftcapes.co.uk

### ISSUE THREAD

**Issue by 0x0231** [JLChnToZ/MCCustomSkinLoader#65]
Can you add support for capes from that website?
 This not works with the CustomSkinAPI because needs the player's uuid.

The api call is pretty simple:
```
http://minecraftcapes.co.uk/getCape/{UUID}
```

**Comment by xfl03** [comment]
Could you provide a UUID for example?

**Comment by 0x0231** [comment]
For example the uuid from a guy named user is: '`ef5db304-c368-4108-9a35-2fd0a072b73d`'
The API call need to be without the dashes, eg:
```
http://minecraftcapes.co.uk/getCape/ef5db304c36841089a352fd0a072b73d
```

As this page only work with premium users (it's like optifine but for custom capes), for get the UUID you need to verify with the Mojang API.

Using the Mojang API for get the UUID will be:
```
https://api.mojang.com/users/profiles/minecraft/{USERNAME}
https://api.mojang.com/users/profiles/minecraft/user
```

**Comment by xfl03** [comment]
# How to use minecraftcapes.co.uk
- Turn on `forceLoadAllTextures`
```json
"forceLoadAllTextures": true
```
- Add it in `loadlist`
```json
{
  "name": "minecraftcapes",
  "type": "legacy",
  "cape": "http://minecraftcapes.co.uk/getCape/{UUID}"
}
```

Please make a review.

**Comment by 0x0231** [comment]
**Tested!**
Works properly in secure and insecure servers!

**Comment by ZekerZhayard** [comment]
Notice that minecraftcapes.co.uk has changed thier API:
```json
{
    "name": "MinecraftCapes",
    "type": "Legacy",
    "checkPNG": true,
    "cape": "https://minecraftcapes.net/profile/{UUID}/cape"
}
```
