### ISSUE TITLE
Clarify the year of copyright statement

### ISSUE THREAD

**Issue by JLChnToZ** [JLChnToZ/MCCustomSkinLoader#66]
Hi,
I think we should clarify the copyright statement, as I am the one who start this project but no longer contribute after transferring to you to maintain, but I suddenly see the copyright statement does not mention this (looks like I am still maintaining this project).

Therefore, I think the copyright statement should split up to 2 parts like this:
```
Copyright © 2013-2014 Jeremy Lam "JLChnToZ".
Copyright © 2014-2019 xfl03.

... (the GPL header here)
```

Thanks.

**Comment by xfl03** [comment]
Thanks for your advice, I updated the copyright statement. Please make a review.

**Comment by JLChnToZ** [comment]
OK, thanks for updating
