### ISSUE TITLE
【特性请求】支持由服务器下发每个玩家的皮肤加载点

### ISSUE THREAD

**Issue by Simba98** [JLChnToZ/MCCustomSkinLoader#67]
我注意到了Issue #22 
能不能实现不同的玩家由不同的源加载皮肤，并且列表由服务器登陆时下发？
比如说A用甲站，B用乙站，C用原版。
目前有一个优先级列表，如果设成Mojang -> 甲 ->乙的话：那如果原版里面就有一个玩家叫A，A的皮肤就会被原版覆盖了。
而这个事情又没法通过预先内置于客户端的配置文件/LocalSkin解决，因为总有新玩家加入。
如果能加点指令就更好啦：比如说/csl changeskin PlayerName [LoadPoint]，例如：
/csl changeskin PlayerName Mojang
/csl changeskin PlayerName MySkinServer
至于是重登录生效还是立刻生效什么的，这个都没关系啦。

**Comment by xfl03** [comment]
直接使用插件修改回传给客户端的GameProfile即可
或者实现一个返回对应Profile的CustomSkinAPI，只使用这个链接也可以
