### ISSUE TITLE
The game crashes and exits when dying in a world

### ISSUE THREAD

**Issue by sepsol** [JLChnToZ/MCCustomSkinLoader#69]
I don't understand crash reports but from the latest.log I suspected that it might be from Custom Skin Loader. If not, please guide me in the right direction to report this issue to the respective developers of the troubling mod. Here are some useful files:

[crash-2019-10-31_12.19.30-client.txt](https://gist.github.com/SepSol/b0a2785ed951fb7b285456fd39b1844c)
[diagnostic.log](https://gist.github.com/SepSol/d2bb8e33ecc4401642f5fdb71a0d9066)
[debug.log](https://gist.github.com/SepSol/ff2172de8aa52011eb66629b60130a26)
[latest.log](https://gist.github.com/SepSol/407232e878c49bfefdaab81cb2833132)

**My specs:**
- Minecraft 1.14.4
- Forge 28.1.70
- OptiFine HD U F4
- CustomSkinLoader_Forge-14.11

**Steps to reproduce:**
1. open the game
2. create a new world
3. die
4. game crashes with exit code of -1 (0xffffffff) before allowing you to choose 'respawn'
5. now launch the game again and select 'respawn' to continue playing

**Comment by xfl03** [comment]
Why do you think CustomSkinLoader made this crash?
I didn't find any evidence about it.
~P.S. It looks like my another mod MoreCrashInfo works wonderfully.~

**Comment by sepsol** [comment]
I've sent it to some other mod first and they guided me and said that they are suspicious of one of these mods:
- Custom Skin Loader
- Console Experience
- Just Fashion

I created an issue for all of you. It seems like the problem was from Just Fashion mod and it's now fixed in the latest update, so I'm gonna close this one. Thanks for responding though!
