### ISSUE TITLE
请求建议修改自动清理缓存的时机

### ISSUE THREAD

**Issue by ZekerZhayard** [JLChnToZ/MCCustomSkinLoader#70]
如果上一次游戏进入人较多的服务器且游戏时间较长，缓存文件产生过多，不出意外，目前 CustomSkinLoader 的缓存是在 `customskinloader.CustomSkinLoader` 被第一次加载的时候清理的，也就是在第一次进入世界时，会造成较长时间的皮肤不加载的状况。  
我建议，把自动清理缓存的时机改成退出游戏时清理。

**Comment by xfl03** [comment]
已改为在游戏初始加载阶段进行清理
Commit：https://github.com/xfl03/MCCustomSkinLoader/commit/779e25f83742801cb3694bd297f24a13ebe6e0ef
