### ISSUE TITLE
CustomSkinLoader无法用于服务器

### ISSUE THREAD

**Issue by HeartyYF** [JLChnToZ/MCCustomSkinLoader#8]
在服务器中无法加载皮肤（盗版服）

**Comment by xfl03** [comment]
具体状况？ 调试信息？
无forge下测试，完整控制台输出贴过来。

**Comment by xfl03** [comment]
spigot/paperspigot？

**Comment by xfl03** [comment]
已确认是spigot/bukkit插件兼容问题，这锅我不背
http://www.mcbbs.net/forum.php?mod=redirect&goto=findpost&ptid=269807&pid=10040504
