### ISSUE TITLE
1.14.4 Head icons not shown up on tablist 

### ISSUE THREAD

**Issue by khanghh** [JLChnToZ/MCCustomSkinLoader#80]
In version 1.12.2 It's work fine, but in version 1.14.4 and up the head icons have not been shown up in the tab list.

**Comment by xfl03** [comment]
It has been fixed, please use the latest snapshot. #71 
### Download
- Forge https://csl.littleservice.cn/mods/CustomSkinLoader_Forge-14.12-SNAPSHOT-109.jar
- Fabric https://csl.littleservice.cn/mods/CustomSkinLoader_Fabric-14.12-SNAPSHOT-109.jar

This mod can be used in 1.8-1.15.2.
