### ISSUE TITLE
[Feature Request] Server-side mod

### ISSUE THREAD

**Issue by Troodon04563** [JLChnToZ/MCCustomSkinLoader#83]
I'd really like a server-side mod since I have a cracked server with my friend and I bought minecraft but can't use my skin because the server is in offline mode, I know of some plugins for that but we're using Fabric for the Carpet Mod. This mod is really nice, but a server-side mod would be even better.

**Comment by xfl03** [comment]
This mod can be used in Fabric modded client, please have a try.

**Comment by KaguraXun** [comment]
I have the same problem，I uesd it in fabric server but can’t find the folder name CustomSkinLoader/LocalSkin
没有报错但是没有皮肤文件夹，是fabric的mod服。

**Comment by ZekerZhayard** [comment]
@KaguraXun CustomSkinLoader 目前仅是客户端模组，无需装进服务端

**Comment by xingxing2008** [comment]
我们需要一个服务端mod （如果可以实现） Pls

**Comment by ZekerZhayard** [comment]
@xingxing2008 现在已经存在服务端插件/ Mod ：
- Spigot: [SkinRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/)
- Fabric: [FabricTailor](https://www.curseforge.com/minecraft/mc-mods/fabrictailor)

以及客户端和服务端都需要使用的 [Authlib-Injector](https://github.com/yushijinhun/authlib-injector)
