### ISSUE TITLE
Skin online doesn't work [1.12.2]

### ISSUE THREAD

**Issue by CommunistSylas** [JLChnToZ/MCCustomSkinLoader#85]
I have a problem with the mod, check how to put the skin online, I also saw in curseforge what some comments said that for the skin to be seen online the other player must also install the mod, I also know that the mod is client side only, so could you know what I am doing wrong so that my skin is not seen on the server with my friends? They have the mod, same version all, I tried to put a skin on a friend in little skin, the page that says on curseforge, and neither I can see his or mine.

**Comment by xfl03** [comment]
@tnqzh123 May be LittleSkin's fault.

**Comment by tnqzh123** [comment]
> @tnqzh123 May be LittleSkin's fault.

Yes. We have a cache problem which lead to the textures loading failure. It will be solved ASAP. Sorry for the inconvenience.

**Comment by tnqzh123** [comment]
> Yes. We have a cache problem which lead to the textures loading failure. It will be solved ASAP. Sorry for the inconvenience.

@CommunistSylas The problem had been solved. Please set your textures again on LittleSkin to update your cache. Thank you for supporting LittleSkin.

**Comment by CommunistSylas** [comment]
Thanks for the quick reply
