### ISSUE TITLE
Doesn't work on 1.12.2 (forge)

### ISSUE THREAD

**Issue by Nyaaki** [JLChnToZ/MCCustomSkinLoader#89]
When I first start this plugin, everything works fine, but after I disconnect and reconnect, the plugin doesn't do anything and also after restarting the game.

**Comment by xfl03** [comment]
Please provide `CustomSkinLoader.log` and `fml-client-latest.log`.

**Comment by xfl03** [comment]
You can reopen this issue after providing log file.
