### ISSUE TITLE
CSL does not support Citizens' skin. CSL不支持默认Citizens皮肤加载方式。

### ISSUE THREAD

**Issue by k-jiang** [JLChnToZ/MCCustomSkinLoader#9]
EN:
Minecraft client does not load Citizens NPC skin once have CSL installed. Since Citizens uses a Player-like entity to represent its NPCs in Craftbukkit / Spigot server, the default CSL mechanism may override the custom NPC skin which uses the default Mojang API.
Citizens is the most used NPC plugin by many Minecraft servers (over 15,000 servers use according to MCStats.org), so it might be a very good idea to add support to it. Thank you!

Tested CSL version: 1.9-13.3a
Minecraft version: 1.9
Load by: Forge mod loader 12.16.0.1811
Server version: Spigot 1.9 R0.1
Citizens version: Citizens 2.0.17 build 1343
(note: NPC skin loads normal without CSL installed)

ZH-CN:
安装CSL后，Minecraft客户端停止显示Citizens NPC的皮肤。因为Citizens NPC采用玩家外形的NPC并使用默认Mojang API显示自定义NPC皮肤，CSL可能会覆盖掉这套机制并导致无法显示NPC皮肤。
Citizens是最多人使用的Minecraft服务器NPC插件（根据MCStsts.org，超过15,000台服务器在运行Citizens），所以请考虑在CSL中加入Citizens皮肤支持，谢谢！

测试CSL版本：1.9-13.3a
Minecraft客户端版本：1.9
加载方式：Forge mod loader 12.16.0.1811
服务器版本：Spigot 1.9 R0.1
Citizens版本：Citizens 2.0.17 build 1343
（备注：NPC皮肤在不安装CSL的情况下能正常显示）

**Comment by xfl03** [comment]
可以加我QQ 帮我做点测试吗？

**Comment by k-jiang** [comment]
好啊，qq号已发送到你的hotmail邮箱

**Comment by xfl03** [comment]
Fixed: 1dbfa30
