### ISSUE TITLE
Local skin is not loading (log attached)

### ISSUE THREAD

**Issue by KuzMaxOriginal** [JLChnToZ/MCCustomSkinLoader#94]
Just placed [KuzMax.png](https://user-images.githubusercontent.com/24495585/83556293-4b56cf80-a518-11ea-9bc4-42152064524e.png) into .minecraft\CustomSkinLoader\LocalSkin\skins, and instead of local skin, I still see my Mojang's one.

My player's username is KuzMax.

Attaching log:
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/4718974/CustomSkinLoader.log)

**Comment by KuzMaxOriginal** [comment]
Mod's version: latest current
Fabric version: latest current (fresh installed)
Minecraft version: 1.15.2

**Comment by KuzMaxOriginal** [comment]
Moreover, top layers are not loading at all, so instead of this:

![image](https://user-images.githubusercontent.com/24495585/83556615-e2238c00-a518-11ea-93e0-fba7cb6d8414.png)

I see this:

![image](https://user-images.githubusercontent.com/24495585/83556643-f2d40200-a518-11ea-94c9-9b2c2d9b121e.png)

(without mod there's no such an issue)

**Comment by KuzMaxOriginal** [comment]
Regarding skin overlays, the problem is not related to this mod.

I finally managed to get this work, but I had to remove everything in CustomSkinLoader.json `loadList`, except `LocalSkin` entry. I think something's wrong with the loading priority.

**Comment by xfl03** [comment]
Skin from Mojang is loaded in highest priority. You can modify `loadList`.

**Comment by KuzMaxOriginal** [comment]
It's a good idea to mention this in docs under LocalSkin section, because it confuses users a lot
